### ISSUE TITLE
[Actividades EdX] Error page not found

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2333/foro-2019-2#1]
Hola ! 

Al intentar re-digirme a los links de las actividades por medio del sitio del curso, 2, 3 y 4 me retorna un error de page not found. Esto no sucede con la actividad 1.

Adjunto foto captura con el mensaje de error:

![image](https://user-images.githubusercontent.com/20147482/62991576-18730c00-be1e-11e9-89f3-572dd3ee40f6.png)

No es como si las fuese a realizar por lo pronto, pero quería informarlo de todas maneras.

Saludos!!

**Comment by Geeermy** [comment]
¡Hola Felipe!

Acabo de verificar el tema. Muchas gracias por informarlo.

Pondré al profesor al tanto para poder solucionar el tema a la brevedad.

¡Que estés bien! :)

**Comment by Geeermy** [comment]
¡Hola!

Ya debería estar OK. ¿Me lo puedes confirmar?

**Comment by frvalenzuela** [comment]
Hola !

Si ahora se ven las cuatro sin problema. 

Muchas gracias !!!
