### ISSUE TITLE
[Tarea1] Duda amount programas concurrentes

### ISSUE THREAD

**Issue by augustoas** [IIC2333/foro-2019-2#10]
Hola ! Acá tengo una duda de lo que hay que hacer.

Por ejemplo si el máximo de programas concurrentes es 5 y hay que correr 8 programas...

- Se espera que se ejecuten 5 programas primero, que todos estos terminen y después ejecutar los 3 que faltan? 

- O que se empiecen a ejecutar 5 y si alguno de estos termina, sin necesidad que todos terminen, se empiece a ejecutar otro que estaba en cola de inmediato?

Saludos !

**Comment by Geeermy** [comment]
¡Hola!

Dado que no dimos detalles de ese punto, pueden hacerlo de ambas formas. **NO OBSTANTE LO ANTERIOR**, lo más correcto sería que se vayan creando procesos dinámicamente a medida que terminan los otros ya que, en teoría, "hay espacio" para ejecutar (entre comillas porque en el fondo dependerá de la cantidad de CPUs que estén libres... pero ustedes no se tienen que preocupar de eso).

¡Mucho éxito!
