### ISSUE TITLE
[Tarea 1] Input en los Tests

### ISSUE THREAD

**Issue by bgsamilla** [IIC2333/foro-2019-2#12]
En el readme que incluyeron en los test dice lo siguiente:
Test 1: ./crexe input.txt output.txt 10
Test 2: ./crexe input.txt output.txt 10
Test 3: ./crexe input.txt output.txt
Con respecto a eso tengo unas dudas. Por enunciado el comando de ejecución tiene el siguiente formato:
./crexe input output amount [max] [-t]
Donde [max] y [-t] son opcionales.
...
El output del test 2 tiene un ejecutable que se corta a los 10 segundos, sin embargo mi programa dice que corre durante 15 segundos (Lo cual viendo el código de dicho ejecutable es así). Lo que creo que pasa en este caso es que le falta otro 10 al comando de ejecución (El parámetro [max] que regula el tiempo), para que se corte dicho ejecutable.

En cuanto al test 3 mi programa se cae y es por que le falta el parámetro amount que según enunciado no es opcional por lo que no manejé el caso en el que no estuviera presente.

¿Podrian revisar esto?. 
Para hacer los ajustes correspondientes.

Saludos!

**Comment by IchottMano** [comment]
Hola!
Efectivamente, en los tests faltaba el parámetro **amount**, pueden ponerle el valor que quieran, no es pertinente para el output del programa en sí.
Saludos y muchas gracias!

**Comment by kenzoak** [comment]
Hola! tenemos que manejar el caso en el que no se incluya el parametro amount, o podemos asumir que siempre va a estar? 
Además, cual sería el input correcto del test 2 para que entregue el output?
Saludos

**Comment by Geeermy** [comment]
¡Hola!

Asuman que siempre estará, no los queremos complicar con eso.

¡Éxito!
