### ISSUE TITLE
wait() y procesos zombie

### ISSUE THREAD

**Issue by gnacrur** [IIC2333/foro-2019-2#13]
Hola, tengo un par de dudas de materia que surgen por la tarea. Tengo una confusión con como evito quedarme con procesos zombies cuando tengo más de un hijo a la vez. Mi idea es ir haciendo forks, para poder ejecutar los programas externos concurrentemente, a través de un ciclo. Lo que no se es como hacer wait para esperar los procesos simultáneamente sin que mi parent se detenga antes de alcanzar a decirle que espere a los demás también. Quizás esto no tiene mucho sentido y en ese caso mi duda recaería en como puedo ejecutar muchos procesos a la vez sin tener el riesgo de que queden como zombies.  
Ojala alguien me pueda aclarar un poco los conceptos para poder seguir avanzando con mi tarea. Gracias!

**Comment by IchottMano** [comment]
Hola!
Quizás viendo la página [man waitpid](https://linux.die.net/man/2/waitpid) encuentres lo que necesitas 😉 
Espero te sirva!
Saludos

**Comment by gnacrur** [comment]
@IchottMano Gracias por la respuesta! No estoy seguro si te refieres a waitpid(0,...), si no entendí mal al entregarle 0 espera a cualquier child. No se si eso significaría que los child corren en paralelo y el parent se queda esperándolos a todos. ¿O en realidad solo espera a 1 y después debo pedir que espere a otro cualquiera? No se si estoy muy perdido, demasiada información nueva.

**Comment by IchottMano** [comment]
Hola!

Disculpa la demora en la respuesta, el waitpid no tiene nada que ver con que los hijos corran en paralelo o no, por lo que no debes preocuparte por eso. Además, la función sólo espera a un hijo.

Saludos!
