### ISSUE TITLE
Execvp y casos prueba

### ISSUE THREAD

**Issue by nmaturana97** [IIC2333/foro-2019-2#14]
Tenia una duda con respecto al funcionamiento de este.
Tenía unos casos que habia creado con python3 y ls, y me funcionaba correctamente.
Sin embargo, al probarlo con los test me di cuenta que los hijos hacian que el proceso volviera a la linea donde habia sido ejecutado el exec y no entiendo por qué esto pasa.
Me podrian aclarar esto?

En especifico hago esto:
`execvp(cmd, args);
printf("hola");`
e imprime hola.

**Comment by bgsamilla** [comment]
También me pasó.
Intenta compilar de nuevo los ejecutables o correr el siguiente comando: chmod u+x ejecutable
Por ejecutable me refiero a idler y usseles
Saludos!

PD: No soy ayudante :P

**Comment by nmaturana97** [comment]
Ahi me funciono, gracias. 
Igual, ojala digan algo al respecto los ayudantes.

**Comment by IchottMano** [comment]
Hola!

El hecho que te devuelva a la línea despues de crear el exec se debe a que exec no pudo completar, debido a un error. 
Probablemente se debió a que efectivamente no estaban los permisos en los archivos para ser ejecutados, lo cual se resuelve con el comando que dió @BSamilla .
Para la corección de la tarea, pueden asumir que sus programas tendrán permisos para ejecutar cualquier proceso.

Saludos!
