### ISSUE TITLE
[Tarea 1] Ubicación de los ejecutables

### ISSUE THREAD

**Issue by daleal** [IIC2333/foro-2019-2#15]
Hola! Para la corrección de la tarea, puedo asumir que la llamada a los ejecutables será relativa a la ubicación de `crexe` y no del archivo de input? Me explico. Imaginemos que en la raíz del repositorio tengo mi ejecutable `crexe` y que tengo una carpeta que se llama `tests`. Dentro de la carpeta `tests` tengo un archivo `input.txt` cuyo contenido es el siguiente:

```text
2
2 ./executable1 arg1 arg2
0 ./executable2
```

Puedo asumir que `executable1` y `executable2` van a estar en la raíz del repositorio en el mismo lugar en que está `crexe`? O podría ser que estén dentro de la carpeta `tests`? Y en caso de que `executable1` y `executable2` estén en la carpeta `tests`, puedo asumir que el contenido de `input.txt` será el siguiente?

```text
2
2 ./tests/executable1 arg1 arg2
0 ./tests/executable2
```

(Obviamente esto no aplica para programas que estén en el `PATH`).
No sé si se entiende mi duda, muchas gracias de antemano!

**Comment by Geeermy** [comment]
¡Hola Daniel!

Sí, asume todo relativo al ejecutable. No nos molestaremos en hacer todo relativo al archivo de entrada, dado que esto añadiría una dificultad que no se alínea con lo que queremos evaluar en la tarea.

¡Éxito! :grin:

**Comment by daleal** [comment]
Gracias!
