### ISSUE TITLE
Execution Time

### ISSUE THREAD

**Issue by benjamimo1** [IIC2333/foro-2019-2#16]
Hola! Queria consultar cual es la mejor manera de cronometrar los procesos:

a) Built in function que reporte el tiempo total
b) Inicializar 2 instancias de tiempo (al principio y al final) y restarlas

**Comment by Geeermy** [comment]
¡Hola!

La respuesta oficial es: lo que te acomode más. La resta del tiempo de término y de inicio es más que suficiente para nosotros. :)

¡Éxito!
