### ISSUE TITLE
Problema Tarea 1

### ISSUE THREAD

**Issue by jgarcia173** [IIC2333/foro-2019-2#17]
Buenas tardes, 
Soy un alumno de intercambio y estoy teniendo problemas para hacer la Tarea 1. Quería saber s si se me podría poner en contacto con un ayudante para así poder realizarla correctamente. 
Mi correo es jgarcia17@uc.cl. 
Muchas gracias.

**Comment by Geeermy** [comment]
¡Hola!

Conversaremos con el equipo y te contactaremos para ver qué se puede hacer.

¡Ánimo!
