### ISSUE TITLE
Problema ejecutable

### ISSUE THREAD

**Issue by tanavarrete** [IIC2333/foro-2019-2#18]
Hola, 
al tratar de hacer correr alguno de los ejecutables de la tarea me sale el siguiente error,
 -bash: ./idler: cannot execute binary file
he buscado por todos lados que puede ser y no he encontrado nada.
que puede ser?
gracias!

**Comment by IchottMano** [comment]
Hola!
Intenta con la solución dada en la issue #14 
Saludos!
