### ISSUE TITLE
Duda Bonus

### ISSUE THREAD

**Issue by jgespinosa10** [IIC2333/foro-2019-2#19]
Para el bonus se nos pide que hagamos todo el programa como threads, o que hagamos una de las funcionalidades que debe tener el programa principal como un thread? Por ejemplo, matar un proceso después de un tiempo o medir cuanto es el tiempo con threads.

**Comment by IchottMano** [comment]
Hola!
La idea de la versión con threads es que hagas una funcionalidad por medio de estos, como los ejemplos que diste.
Saludos!
