### ISSUE TITLE
[Actividad 1]  Modo kernel en MS-DOS?

### ISSUE THREAD

**Issue by NoemiCC** [IIC2333/foro-2019-2#2]
Hola,
Estoy haciendo la Actividad 1 y en una de las preguntas me salen las siguientes correcciones:

"Las primeras versiones de MS-DOS eran para un chip, el Intel 8088, que **no poseía modo kernel**"
"En las primeras versiones de MS-DOS todos los programas (juegos, procesadores de texto, editores, compiladores, etc) **ejecutaban en modo kernel**. Cualquier falla en ellos bloqueaba todo el sistema y requería reiniciar."

Entonces no me quedó claro cual es correcta. Las primeras versiones de MS-DOS tiene modo kernel o no?

Gracias.

**Comment by cruz** [comment]
Hola @NoemiCC ,
Talvez la primera frase se puede prestar para confusión:

> "Las primeras versiones de MS-DOS eran para un chip, el Intel 8088, que **no poseía modo kernel**"

Lo que quiere decir es que el Intel 8088 (introducido en 1979) **no poseía un modo de protección para diferenciar entre _kernel_ y _user_**. La consecuencia de esto que **sólo existe un modo posible: el modo _kernel_**, y éste era el modo bajo el cual corrían todos los programas. En particular MS-DOS fue diseñado para estos chips, por lo tanto la API permitía que todos los programas pudieran acceder directamente al _hardware_, lo que podía ser en cierto aspecto muy eficiente (accesos inmediatos sin pasar por ninguna otra capa de _software_), pero también muy riesgoso (cualquier _bug_ en el programa de usuario podría potencialmente bloquear todo el sistema).

El primer chip de Intel que incluyó un modo de protección entre modo _kernel_ y modo _user_ fue el 80286 (de 1982).

Referencias:
https://www.quora.com/What-are-CPU-real-mode-and-protected-mode
https://en.wikipedia.org/wiki/Protected_mode
https://www.geek.com/chips/difference-between-real-mode-and-protected-mode-574665/

Espero que te haya ayudado. Corregí la redacción de la primera alternativa, y les dí un intento más.

Saludos

**Comment by NoemiCC** [comment]
Gracias, ahora me queda claro.
