### ISSUE TITLE
Prueba en servidor

### ISSUE THREAD

**Issue by gnacrur** [IIC2333/foro-2019-2#20]
Hola, quería probar mi tarea en el servidor pero se supone que no deberían haber archivos binarios. No estoy seguro pero creo que si la pruebo en el servidor se van a crear archivos binarios en la carpeta. Además supongo que no deberíamos subir programas para testear ni nada pero creo que son necesarios para probarlo. Alguna idea de como podemos hacer esto asegurándonos de que no se vaya a crear ni quedar nada que nos pueda causar el descuento?
Además, con los test, pese a haber hecho lo de la ayudantía 14 sigo teniendo problemas. Los hijos ejecutan la lineas después del exec(). No se si esto es normal o no. Puse un exit() justo después del exec entonces mi output sale bueno pero no se si debiese comportarse así. (Estoy trabajando en windows con Linux Subsystem). Gracias!

**Comment by IchottMano** [comment]
Hola!
En primer lugar, puedes subir o crear archivos binarios en el servidor, solo que estos no deben estar ahí cuando nosotros recolectemos la tarea (plazo establecido).
En segundo lugar, intenta usando la solución de esta issue #14 y dime si te funciona.
Saludos!

**Comment by gnacrur** [comment]
@IchottMano hola, cuando dije ayudantía 14 me refería a issue 14 perdona. Lo probe y no se arreglo. Ahora me di cuenta que solo me falla cuando el los argumentos entregados contienen palabras. Que es el caso de las lineas "2 ./idler 10 hello" y "4 ./useless german ricardo kevin felipe". 
Edit: ya lo solucioné, me faltaba agragar NULL al final del array que le entregaba a execvp.
