### ISSUE TITLE
Problema al subir al servidor

### ISSUE THREAD

**Issue by gnacrur** [IIC2333/foro-2019-2#21]
Hola, estoy teniendo problemas con los permisos para subir una carpeta al servidor. No se si quizás estoy haciendo algo mal o me falto hacer algún paso antes:
![image](https://user-images.githubusercontent.com/42191903/63803152-3773a280-c8e2-11e9-9901-f558dff3dceb.png)

**Comment by Geeermy** [comment]
¡Hola!

Sin ánimos de ser pesado: por favor, revisa el material de la ayudantía. Se mostró paso a paso cómo subir la tarea al servidor. El problema que tienes ahí es que estás tratando de subir archivos de tu máquina local **estando en el servidor**. En el servidor no existe tu máquina local (en este caso, `Desktop/T1`), por lo que no te va a dejar ejecutar dicho comando.

Tienes que ejecutar el mismo comando (sin `sudo` está bien) pero sin conectarte por `ssh` antes, ya que eso se lleva a cabo en el comando mismo (cuando indicas que el destino es una carpeta **dentro** del servidor). Incluso, puedes ubicarte en la carpeta `Desktop` y hacer `scp -r T1 ...` directamente.

Espero haber sido claro y, nuevamente, revisa el material con detención porque este detalle sí estaba mencionado.

¡Quedo atento!

**Comment by gnacrur** [comment]
Hola, si lo revisé, de hecho de ahí saque la linea que ejecute en la foto, pero al menos para mi no estaba tan claro como estaba explicado a la ayudantía. Probablemente si hubiese ido a la ayudantía no hubiese tenido problemas pero no pude ir. La explicación que pones acá esta muy clara así que muchas gracias. De todos modos lo terminé haciendo por Filezilla, espero que eso no sea problema.

**Comment by Geeermy** [comment]
En la _slide_ de "consideraciones" estaba el punto, pero claro, quizás es más entendible viéndolo en vivo. En fin, mientras hayas logrado subir tu tarea, todo ok (no hay problema con Filezilla, aunque siempre sirve manejarse con los comandos en consola (: ).

¡Que estés bien!
