### ISSUE TITLE
Problema en manejo del numero de argumentos

### ISSUE THREAD

**Issue by kenzoak** [IIC2333/foro-2019-2#22]
Hola!
Estaba intentando controlar las variables que se instancian en mi programa dependiendo de si se ingresa el parámetro `<max>` o no. Lo estaba haciendo con argc al comienzo del programa así:
` if(argc == 5)
{
 max_time = atoi(argv[4]);
}` 
He probado de distintas maneras, cambiando el `==` por `<=>` pero  cada vez que entra en este if se me cae el programa con un segmentation fault. 
Gracias!

**Comment by Minjor** [comment]
Hola, a mi me salió haciendolo en 2 lineas en vez de 1, la primera con char* max = argv[4] y despues le aplico atoi() a esa variable
