### ISSUE TITLE
Duda Resultados (0 - 1)

### ISSUE THREAD

**Issue by camichavez** [IIC2333/foro-2019-2#23]
Hola! perdón si ya lo preguntaron (busqué y no encontré), pero quisiera saber si estoy entendiendo bien cuando el resultado en el .csv es 0 o 1
1) es 0 si es que el programa alcanzó a ejecutarse correctamente en el tiempo [max] y si es que se había estado ejecutando correctamente y "lo maté" a los [max] segundos.
2) es 1 si el programa no se ejecuta correctamente o si el usuario provoca alguna interrupción (ctrl + C).

Además, los segundos están aproximados hacia arriba o hacia abajo? por ejemplo: 3,5 es 3 o es 4?

Muchas gracias!!

**Comment by Geeermy** [comment]
¡Hola Camila!

1. En realidad, es 1 si la ejecución es exitosa solamente. Si te pasas del tiempo máximo, o bien se interrumpe por CTRL + C, se considera `resultado = 0`. Eso es lo que está expresado en el enunciado.

2. Puedes aproximarlos hacia arriba, no será problema porque consideraremos un rango de +- 1 segundo a todos los valores (y los programas externos a ejecutar tendrán un tiempo bastante establecido).

¡Mucho éxito! :)
