### ISSUE TITLE
Problema pedir memoria en el servidor

### ISSUE THREAD

**Issue by ignacioaraya1995** [IIC2333/foro-2019-2#24]
Hola, he estado testeando el codigo en el servidor y me tira el error.
**Core Dump/Segmentation fault** que es un problema especifico causado cuando el programa solicita memoria que no le pertenece. En mi computador funciona perfecto, pero el servidor tira ese problema. Cuando corrigan se tendra acceso a la memoria?

Gracias

**Comment by IchottMano** [comment]
Hola!
En el servidor efectivamente tienes acceso a pedir memoria, sin embargo en alguna parte de tu código debes estar accediendo a memoria que no te pertenece o intentando liberar memoria que ya está liberada. Aquí el problema no está en el servidor, sino que en tu código.
Te recomiendo usar valgrind en el servidor para revisar que error es el que genera tu programa.
Saludos!
