### ISSUE TITLE
Nombres de procesos

### ISSUE THREAD

**Issue by mundurragac** [IIC2333/foro-2019-2#25]
Podemos asumir que los nombres de los procesos van a ser de menos de 255 caracteres? Para poder asignarle memoria no dinámica a la variable del nombre.

**Comment by Geeermy** [comment]
¡Hola!

Esto está explicitado en el enunciado: todo proceso puede tener un nombre de **hasta** 256 caracteres. Por ende, puedes pedir esa misma cantidad de memoria siempre sin complicarte más.

¡Éxito!

**Comment by mundurragac** [comment]
Perdón, no lo había visto! Gracias

**Comment by Geeermy** [comment]
No hay problema. :-)
