### ISSUE TITLE
Consulta funcionamiento free + arrays

### ISSUE THREAD

**Issue by gnacrur** [IIC2333/foro-2019-2#29]
Hola, estaba intentando de liberar la memoria del array de bursts que tiene cada proceso en mi programa. Este array era inicialmente de strings, lo que funcionaba con normalidad. El problema es que cuando intentaba liberarlos me salía lo siguiente: 
`warning: passing argument 1 of ‘free’ makes pointer from integer without a cast [-Wint-conversion]
         free(proceso -> bursts[j]);`
En donde bursts[j] corresponde a una de las posiciones de la lista que guardaba un entero. Pense que el error era que debía entregarle al free un puntero, por lo que cambie todo a que el array ahora sea de punteros que apuntan a un entero. El problema es que ahora me sale segmentation fault al intentar liberar el primer valor. 
No se de que forma debería hacerlo ni como sería lo más correcto pero quería saber si es que hay algún error evidente en lo que estoy haciendo o alguna razón más simple por la que este teniendo el error y que yo no vea. Cualquier ayuda es apreciada, gracias!

**Comment by Geeermy** [comment]
¡Hola!

Hmm, es difícil ver dónde podría estar el error sin ver cómo haces la asignación de memoria.

¿Intentaste liberando el arreglo de bursts de una sola vez? Por ejemplo, `free(procesos -> bursts)`? (Esto antes de tener un arreglo de punteros).

Trata probando con eso y cuéntame cómo te va.

**Comment by gnacrur** [comment]
Haciendo eso funcionó! No entiendo bien porque eso si, pensaba que tenía que recorrer un arreglo para poder liberarlo. Muchas gracias!

**Comment by Geeermy** [comment]
Sí, pero eso es cuando pides memoria por cada elemento del arreglo (arreglo de punteros, o puntero a punteros). En tu caso, solo tenías el puntero principal con el contenido directo, lo que hace innecesaria la liberación de memoria (ya que no son direcciones de memoria solicitadas... son contenido directamente).

Espero que se entienda. :-)

¡De nada!
