### ISSUE TITLE
Uso del indicador nº de variables al comienzo de cada linea

### ISSUE THREAD

**Issue by benjamimo1** [IIC2333/foro-2019-2#3]
Hola! Estoy leyendo las lineas del archivo input.txt linea por linea y usando eso directamente como comando a ejecutar con C. Dado esto, es realmente necesario el valor "numero de argumento" que esta al comienzo de cada linea? Pregunto si es que quizas hay algun uso que no estoy viendo.

**Comment by IchottMano** [comment]
Hola!
La idea del "numero de argumento" es para la gente que lea el archivo por medio de un loop que lee la cantidad de líneas especificadas, pero tambien es posible hacerlo sin este número.
Aparte de esto, no tiene ningun uso secundario, por lo que no debes preocuparte.
Saludos!
