### ISSUE TITLE
[Tarea 2] Ingresar Todos los Procesos al Queue

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2333/foro-2019-2#30]
Hola!

Sería válido ingresar todos los procesos inmediatamente a la cola y agregar un quinto estado? (Como INVALID, por ejemplo) de forma de cambiarlo a READY cuando llegue su tiempo de inicio?

De antemano, gracias!

**Comment by Geeermy** [comment]
¡Hola!

**Como dije en ayudantía** (y como se expresa en el enunciado), es totalmente válido no implementar una cola dinámica (_i.e._ con procesos que van entrando y saliendo según métodos _enqueue_, _dequeue_) y añadir estados adicionales que te permitan modelar a los procesos que todavía no han llegado. A mi parecer, es el mejor acercamiento para no alargar el modelamiento de la simulación.

¡Mucho éxito! :grin:

**Comment by KnowYourselves** [comment]
Grax

**Comment by ignacioaraya1995** [comment]
Hola, es valido tener todos los procesos en un arreglo sin necesariamente construir la estructura Queue?

**Comment by Geeermy** [comment]
¡Hola!

No, **es necesario** tener la estructura `Queue` para la modelación del problema (expresado en el enunciado y en la rúbrica). No obstante, sí es válido que esta estructura contenga únicamente el arreglo de procesos, si se te hace más fácil hacerlo de esa manera.

¡Que estés bien!
