### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by lucianoandresch** [IIC2333/foro-2019-2#31]
¿Podrían subir más tests para probar el programa?

Gracias, saludos cordiales

**Comment by Geeermy** [comment]
¡Hola!

Si me da el tiempo, veré si puedo introducir alguno en esta misma _issue_ durante el fin de semana. No obstante lo anterior, con los dos _tests_ subidos deberían probar casi (si no todos) los casos a considerar. Además, si alguien se anima (o tu mismo) a hacer un _test_ y corroborar con el resto de tus compañeros/as, genial si pueden.

¡Que estés bien!
