### ISSUE TITLE
[T2] Interrupciones

### ISSUE THREAD

**Issue by jnpoblete** [IIC2333/foro-2019-2#32]
Hola, tengo una duda con las interrupciones en ss. Si tengo un proceso corriendo una rafaga de 6 tiempos, de los cuales lleva 5 (5/6). Si otro proceso que estaba esperando termina de esperar justo en este momento, y su próxima rafaga es de 4 tiempos, la cpu compara estos 4 tiempos con los 6 del que está corriendo (largo del burst) o con el 1 restante del mismo (5/6)? Saludos!

**Comment by Geeermy** [comment]
¡Hola! Me di la libertad de cambiar el título para que fuera más explicativo.

En ambas versiones (_short-sighted_ y _long-sighted_) se toma como referencia la ráfaga (o tiempo de ejecución total) **RESTANTE**, es decir, en el ejemplo se das se comparan los 4 tiempos del proceso que termina su espera con el 1 restante del proceso en ejecución, es decir, no se genera interrupción.

Espero haber sido claro. :)

¡Mucho éxito!

**Comment by toalheli** [comment]
Muchas gracias, había supuesto aquello pero queria estar seguro. 

Tengo otra duda al respecto, si se genera una interrupcion, cuando el proceso que ha sido interrumpido vuelve a ejecutar la rafaga, la ejecuta por completo  o lo que le faltaba por ejecutar?. Ejemplo: Un proceso es interrumpido cuando llevaba 4 tiempos de una rafaga de 6 tiempos (4/6), al volver a ejecutar,  ejecuta 6 tiempos o ejecuta solo los 2 restantes?

Saludos!

**Comment by jnpoblete** [comment]
Muchas gracias, había supuesto aquello pero queria estar seguro.

Tengo otra duda al respecto, si se genera una interrupcion, cuando el proceso que ha sido interrumpido vuelve a ejecutar la rafaga, la ejecuta por completo o lo que le faltaba por ejecutar?. Ejemplo: Un proceso es interrumpido cuando llevaba 4 tiempos de una rafaga de 6 tiempos (4/6), al volver a ejecutar, ejecuta 6 tiempos o ejecuta solo los 2 restantes?

Saludos!

**Comment by Geeermy** [comment]
Lo que le falta por ejecutar. Por lo tanto, en tu ejemplo ejecuta las 2 restantes. :)
