### ISSUE TITLE
[Ayudantía 2] Ejemplo Short-Sighted

### ISSUE THREAD

**Issue by camichavez** [IIC2333/foro-2019-2#34]
**EDIT: Lo sientoo, ya entendí, me confundí por la notación de que de 3 a 6 se consideran como 4 tiempos, entonces no fue interrumpido, solo terminó de ejecutar su ráfaga. Gracias de todas formas!**

Hola! (perdón si ya lo habían aclarado en la ayudantía)
Tengo una duda respecto al ejemplo que dan:
![image](https://user-images.githubusercontent.com/37157327/64491019-936eed00-d239-11e9-9152-4aeff76cab86.png)
Si ahí en algún momento se va a empezar a ejecutar P1 con una ráfaga de 4 tiempos, que siempre será menor a 6, correspondiente a la ráfaga de P2, por qué en la imagen siguiente P1 se interrumpe?
![image](https://user-images.githubusercontent.com/37157327/64491033-c74a1280-d239-11e9-8f14-d0a428b2d0fc.png)

Espero se entienda, muchas gracias!

****

**Comment by Geeermy** [comment]
¡Hola Camila!

Lo que destacas en amarillo **no es una interrupción**, las interrupciones suceden cuando un proceso pasa de `RUNNING` a `READY`. ¿Por qué? Porque eso significa que estaba ejecutando pero no pudo terminar por la interrupción, lo que implica que está listo (`READY`) para volver a ser escogido y terminar su ráfaga actual. En cambio, cuando un proceso pasa de `RUNNING` a `WAITING`, es porque **terminó su ráfaga de ejecución actual** y ahora le toca seguir el tiempo de espera (que sería el tiempo _Bi_). 

Si te fijas, el proceso P1 es escogido en _t = 2_ y corre hasta _t = 6_. La primera ráfaga de ejecución _A0_ es igual a 4 y, si restas los tiempos, el proceso P1 ejecuta 6 - 2 = 4 iteraciones, es decir, ejecuta toda la ráfaga _A0_, por lo que le toca pasar al tiempo de espera _B0_.

**Comment by Geeermy** [comment]
PD: Acabo de ver el _edit_, pero de todas formas terminé la respuesta por si a alguien le sirve entender el esquema. :)

¡Mucho éxito!
