### ISSUE TITLE
Problema corriendo el codigo en el servidor

### ISSUE THREAD

**Issue by ignacioaraya1995** [IIC2333/foro-2019-2#35]
Hola, resulta que estoy corriendo el mismo codigo con el mismo input y metodo en mi computador y en el servidor y la forma del output es distinto. 

Saben la causa del problema??

<img width="832" alt="Screen Shot 2019-09-08 at 2 12 35 PM" src="https://user-images.githubusercontent.com/21697653/64491805-eac58b00-d242-11e9-8af9-e13729ced65d.png">

**Comment by Geeermy** [comment]
¡Hola!

A primeras no sabría decirlo...

Primero que todo: ¿estás seguro que lo que está en el servidor es la última versión de tu tarea? Pregunto porque en la imagen del servidor hay una falta de ortografía que pareciera estar corregida en la versión de tu computador.

Si no es eso, me sabría difícil saber qué está pasando. Pareciera que en el servidor está fallando la escritura del archivo, dado que las estadísticas son _casi_ las mismas (el _waiting time_ difiere en una unidad y no se imprime el nombre del tercer proceso... además que todo se imprime como tres veces).

Verifica que sea la misma versión primero y después te sugiero que vayas imprimiendo tus estructuras, para verificar que al menos la inicialización de la simulación esté bien.

Quedo atento. :)

**Comment by ignacioaraya1995** [comment]
Hola!

Estoy seguro que estoy corriendo la última versión de mi programa en el servidor.
Tanto la escritura del archivo como el printf aparecen duplicados, al momento de escribir esto tengo una funcion para imprimir las estadisticas y en el último proceso, se imprimen las últimas 6 líneas de la terminal.

Los valores estan bien, sin embargo no se printea el nombre del último proceso. Todo corre perfecto, fui testeando las estructuras y al printearlo se pone loco, teniendo el mismo código en mi computador funciona perfecto.

¿Alguna idea?

**Comment by Geeermy** [comment]
¿Te aseguraste de compilar de nuevo tu programa en el servidor? Me di la libertad de ver tu código arriba y no vi nada raro (ni siquiera la impresión de la palabra "prosesos" en la imagen de la izquierda, por lo que no me hace sentido que se siga imprimiendo si lo volviste a compilar).

PD: Pude notar que no estás metiendo dentro de la estructura `Queue` el arreglo de procesos como te lo comenté en otra _issue_, que no se te olvide ese detalle. :eyes:

**Comment by ignacioaraya1995** [comment]
Hola, me aseguré de compilar mi programa en el servidor (arreglé el error de ortografía) e igualmente el "Error" de la impresión se mantiene. 

PD: Gracias por notar el detalle del Queue, solucionado.

**Comment by Geeermy** [comment]
Genial lo de `Queue`, quería verificar para que no tuvieras problemas con eso después. :)

Para seguir ahondando más en tu error, noté que tienes **dos** ejecutables: `./scheduler` y `./main` (en el servidor corriste `./scheduler` y en local corriste `./main`). En la carpeta de tu servidor veo que ambos ejecutables existen. ¿Puedes probar corriendo `./main`? (Ya que ese es el que funciona en local).

**Comment by ignacioaraya1995** [comment]
Resulta subí el `main.c `a la carpeta principal y sin uso del MakeFile lo volví a correr y me continua tirando el mismo tipo de output. 

<img width="393" alt="Screen Shot 2019-09-08 at 3 33 47 PM" src="https://user-images.githubusercontent.com/21697653/64492764-14d07a80-d24e-11e9-887c-7eed157f778d.png">

**Comment by Geeermy** [comment]
A ver, por mientras limpia por completo todo lo que esté subido en el servidor y sube nuevamente la carpeta completa que tienes en local. Vuelve a compilar y ejecutar y cuéntame si eso soluciona tu error. 

Si eso no resulta, pasamos a lo siguiente: viendo las estadísticas es claro que el problema no es la simulación en sí, sino que la impresión de los resultados. Por lo tanto, el problema estaría en cómo estás recorriendo el arreglo de procesos al final de la simulación. En vez de usar el método que tienes, trata de hacer la escritura manual al final del programa (no en un `for`, si no que proceso a proceso con `processes[0]`, `processes[1]` y `processes[2]`). Si eso te funciona bien, sabremos al menos que el error está en el método de escritura.

Cuéntame cómo te va haciendo eso.

**Comment by ignacioaraya1995** [comment]
Hice lo que me dijiste y el error persiste, es suuuuuuuuuper raro!

Nose que puede ser, en mi computador no existen problemas.

<img width="1338" alt="Screen Shot 2019-09-08 at 4 00 31 PM" src="https://user-images.githubusercontent.com/21697653/64493103-2c116700-d252-11e9-81c2-b02126b1c366.png">

**Comment by Geeermy** [comment]
Me puse a jugar con el código de tu programa (el de la carpeta "Probando") y verifiqué que los procesos 1 y 2 están perfectos (por ahí hay algún print de más que hace que se repitan algunas líneas, pero la lista en sí está ok), el único problema es que el proceso `P3` está sin nombre, lo que se puede explicar solo por una mala inicialización (o lectura del archivo). Revisa cómo se está llevando a cabo la lectura imprimiendo los _token_ (o como sea que estés haciendo la lectura) en los métodos involucrados, a ver en qué momento pasa que no se asigna correctamente el nombre.
