### ISSUE TITLE
Actividades edX

### ISSUE THREAD

**Issue by nmaturana97** [IIC2333/foro-2019-2#38]
Hola, creo que no entré en el plazo que se debía para el registro en el curso y ahora no puedo hacer el enrollment. La verdad entré al principio del curso desde el celular y como salia: "Si han llegado a este punto es porque han logrado registrarse e inscribirse exitosamente en la plataforma EdX del curso", pense que ya me había inscrito.
Hay alguna forma de hacer el enrollment ahora?

**Comment by SarahEverke** [comment]
Hola, tengo el mismo problema.
¿qué puedo hacer?
Saludos

**Comment by Geeermy** [comment]
¡Hola! Disculpen por no haber contestado antes.

Dado que ninguno de los ayudantes tenemos permisos de administrador en la plataforma y el profesor no vuelve hasta mañana, no podemos hacer mucho más que pedirles que esperen. Obviamente, dado el inconveniente, cambiaremos los plazos de las actividades para que no se vean perjudicados por la situación.

¡Desde ya gracias por su comprensión!

**Comment by SarahEverke** [comment]
Muchas gracias

**Comment by cruz** [comment]
Hola. Ya está actualizado. Pueden inscribirse. Está disponible hasta la actividad 5. Esta semana habilitaré las 6 y 7. El plazo para todas será el día del midterm.
