### ISSUE TITLE
[Proyecto SSOO] - Montar el Disco

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2333/foro-2019-2#39]
Hola!

En la función montar el disco la idea es **montar el disco entero a memoria?** O se espera que accedamos a el a medida que sea necesario?

Saludos!

**Comment by Geeermy** [comment]
¡Hola!

La idea es lo segundo. Lo ideal sería que la función montar establezca en una variable global la ruta del disco.

¡Éxito! :-)

**Comment by KnowYourselves** [comment]
~Salu2~ Gracias!
