### ISSUE TITLE
Uso de fork() vs exec()

### ISSUE THREAD

**Issue by benjamimo1** [IIC2333/foro-2019-2#4]
Hola! Segun la documentacion que he leido, fork genera un child clon del proceso padre y corre en paralelo. Por lo tanto por cada fork que hagamos, duplicamos el numero de procesos corriendo. Dado esto, y que modele mi set de instrucciones como una lista de strings, es posible hacer uso del comando exec(), o debe hacerse uso de fork()? (El cual me genera outputs duplicados de momento)

**Comment by Geeermy** [comment]
¡Hola!

No necesariamente duplicarás los procesos. Si te fijas en los apuntes, puedes diferenciar la ejecución de cada proceso según el valor de retorno de `fork()`: http://iic2333.ing.puc.cl/slides/1-proc.html#/creation-fork-l-q

Si haces un control de flujo haciendo uso de `child_pid` (cuyo valor será distinto para el proceso padre e hijo), puedes evitar que se duplique la cantidad de procesos constantemente, y que el proceso hijo haga algo distinto.

Por otra parte... deberían tener que usar `exec()` para poder ejecutar los programas externos. 👀 Así que no me queda claro por qué no lo usarías.

En fin, espero haber sido claro. Cualquier cosa quedo atento. 😁

**Comment by benjamimo1** [comment]
Hola @Geeermy, gracias por linkear a los apuntes!
Para ejecutar los procesos estoy usando command(), por lo que no me he visto en necesidad de usar exec() (que tengo entendido funciona de manera bastante similar)

**Comment by Geeermy** [comment]
@benjamimo1 Quizás te confundiste y quisiste decir que estás usando `system()` (que recibe `char*  command`). En ese caso, no veo problema.

Solo por si a alguien le interesa ahondar más en `system()` (dado que `exec()` está en los apuntes):

**Funcionamiento de `system()`:** https://www.tutorialspoint.com/c_standard_library/c_function_system.htm

**Diferencia entre `exec()` y `system()`:** https://stackoverflow.com/questions/1697440/difference-between-system-and-exec-in-linux

**Comment by benjamimo1** [comment]
Toda la razon! Usando system. Gracias por la pronta respuesta

**Comment by Geeermy** [comment]
¡De nada!

PD: En general dejamos las _issues_ abiertas hasta la entrega de la tarea, de forma que esto sea de utilidad para todos/as. 😁

**Comment by cruz** [comment]
Hola. Un alcance acerca de `system`. Al lanzar un programa usando `system`, el programa principal espera hasta que el hijo termine antes de continuar. Consideren este ejemplo:

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

int main () {
  system("sleep 20; echo 1");
  system("echo 2");
  printf("Soy el programa principal\n");

  return(0);
}
```

Este programa primera crea un hijo mediante `system` (internamente con `fork` y `exec`) que hace `sleep 20; echo 1`, y solo cuando ese hijo termina entonces crea otro hijo que hace `echo 2`. Por lo tanto ambos hijos nunca ejecutan en paralelo.
