### ISSUE TITLE
[Proyecto SSOO] Destino de cr_load

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2333/foro-2019-2#40]
Hola!

Está función copia archivos hacia el disco, pero no hay ningún argumento que especifique donde. Debemos guardar las cosas en root, o podemos agregar un argumento dest?

Gracias!

**Comment by Geeermy** [comment]
¡Hola!

Déjalo en `root`. Ojo, si es una carpeta, se debe respetar la jerarquía. Por ejemplo, si subes la carpeta `foo` que contiene la carpeta  `bar`, que a su vez contiene el archivo `x`, al subirlo se debe ver así:

```
root
   |-foo
   |  |-bar
   |     |-x
   |-otros archivos del disco
```

Espero que se entienda. :-)

**Comment by Geeermy** [comment]
**Importante:** Modifiqué el comentario anterior ya que noté que me había comido la carpeta `foo`, jeje.

**Comment by KnowYourselves** [comment]
~Ni perdón ni olvido.~ Muchas gracias!

**Comment by MrEarle** [comment]
Que pasa si coincide con alguna carpeta ya creada? Se hace merge o se sobreescribe?

**Comment by KnowYourselves** [comment]
En todas las issues han recalcado lo mismo, que esa clase de cosas quedan a nuestra discreción :eyes:

**Comment by Geeermy** [comment]
¡Hola! Perdón la demora @MrEarle.

Justamente lo que dice @KnowYourselves. Puedes simplemente enviar un mensaje de error indicando que la carpeta ya existe (ya que de todas formas debiese haber un `cr_mkdir` metido por ahí), o bien sobreescribir, lo que se te haga más intuitivo. Lo importante es que lo dejen claro en el `README` y/o documentación, si deciden incluir esta última por el bonus.

¡Mucho éxito!
