### ISSUE TITLE
[Proyecto SSOO] Funcionamiento de cr_mkdir

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2333/foro-2019-2#41]
Hola!

Por lo que entendi de `cr_mkdir` es que este recibe el path de una carpeta a ser creada. Mi pregunta es, que pasa si es que no existen las carpetas intermedias a este path?

Por ejemplo, si ejecutara la función con el path `/foo/bar/carpeta`, pero no existira la carpeta `bar`, deberíamos crearla?, Tirar error?, No precuparnos de este caso?

Saludos!

**Comment by Geeermy** [comment]
¡Hola!

En este caso, citaré lo último que se indica en la sección de "Observaciones" en el enunciado:

> Cualquier detalle no especificado en este enunciado puede ser abarcado mediante supuestos, los que deben ser indicados en el README de su entrega.

Ambas opciones que entregas son válidas, basta con que indiques cómo lo abordaron para que esté bien (y que funcione en el caso básico, claro está). También puede complementar la documentación y el manejo de errores, si deciden hacer algo del bonus.

¡Mucho éxito! :)

**Comment by KnowYourselves** [comment]
~Salu3~ Muchas Gracias!
