### ISSUE TITLE
[Proyecto SSOO] Duda Puntero de Bloque

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2333/foro-2019-2#42]
Hola!

Tengo una duda respecto al puntero de cada bloque. Específicamente respecto a esta parte del enunciado:

![image](https://user-images.githubusercontent.com/26102039/65539040-a4c12600-ded6-11e9-896c-d27e9938d083.png)

Esto hace referencia a que el puntero del bloque es un `unsigned int`?, Que el puntero está guardado dentro de cada bloque?, Ambas?

Gracias!

**Comment by Geeermy** [comment]
¡Hola!

Lo primero. Los bloques no necesitan guardar sus punteros, ya que con el puntero en sí (que sería el número de bloque) los podemos ubicar. Al final, funciona como un _offset_:

```
block_addr = block_ptr * 1024
```

`block_addr`, en este caso, nos ayuda a posicionarnos en el **primer byte** del bloque número `block_ptr` del disco binario. Se multiplica por 1024 ya que cada bloque está compuesto por 1KB (1024 bytes), y el posicionamiento de punteros se hace a nivel de bytes.

¡Espero que se entienda!

**Comment by KnowYourselves** [comment]
Perfecto! Es exactamente como creía que era :smile:, solo me pasó que créi que internamente estaban guardado y con eso no me daban los cálculos.

Gracias!
