### ISSUE TITLE
[Proyecto SSOO] Entradas de directorio de continuación

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2333/foro-2019-2#43]
Hola!

En la explicación de los bloques de directorio se dice que una de las entradas (la última especificamente) esta reservada para ser un directorio de continuación. Mi pregunta es, **solo está entrada puede ser de continuación?**, O podríamos, por ejemplo, tener un bloque de directorio con todas sus entradas (menos `.` y `..`) sean de continuación?

Saludos!

**Comment by Geeermy** [comment]
¡Hola!

La respuesta es lo primero. Todo bloque directorio estará compuesto por dos bloques con entradas. El primero tendrá en su última entrada un puntero a su continuación (además de una entrada con `.` y otra con `..`), mientras que el segundo contiende solo entradas a otros archivos/directorios (esto, según lo descrito en la sección de bloque directorio y en "observaciones", donde en esta última se indica que **todo bloque directorio tiene solo un puntero de continuación**).

Espero que haya quedado claro. :-)

**Comment by Geeermy** [comment]
PD: Tenía la respuesta escrita y se me olvidó publicarla. :hugs:

**Comment by KnowYourselves** [comment]
Gracias!
