### ISSUE TITLE
[Proyecto SSOO] Duda cr_bitmap

### ISSUE THREAD

**Issue by CmPoblete** [IIC2333/foro-2019-2#44]
Hola, cual es el formato que se espera que tenga el output de esta funcion? si cada bloque del bitmap tiene 1KB, debemos imprimir muchas lineas con el estado de cada bloque que representa cierto bloque de bitmap?

**Comment by IchottMano** [comment]
Hola!
No existe un formato específico, son libres de hacer una línea por bloque, una linea cada "n" caracteres, o como ustedes prefieran. Lo importante es que la función efectivamente imprima el contenido de los bloques indicados.
Saludos!

**Comment by DanielCarrascoFalcon** [comment]
Cual se supone que es la diferencia entre binario y hexa si solo son 1s o 0s??
Se espera que pongamos 0x00000001???

**Comment by Geeermy** [comment]
¡Hola @DanielCarrascoFalcon ! No...

Si tu primer byte es 11111111, esto en hexa se verá como 0xFF. Recuerda que cada dígito en hexa representa cuatro dígitos en binario (es decir, cuatro bits), por lo que no verás solo 0's o 1's, vas a ver dígitos desde 0 hasta 9 y letras desde A hasta F.

**Comment by DanielCarrascoFalcon** [comment]
Oka, pero ahí ya no estoy representando todos los bloques posibles (individualmente), porque estoy agrupando de a 4 en el fondo, eso es lo que se quiere lograr??? Obvio que van a haber menos numeros que bloques posibles...
Ah y otra cosa lo de stderr no me queda muy claro, se imprime solo en caso de algún error?? si me pudieras orientar un poquito porfaa
Muchas gracias!!

**Comment by Geeermy** [comment]
Obvio, es una forma de abreviar lo que se imprime del bitmap (se divide en 4 la cantidad de dígitos a imprimir, lo que es bastante considerable), además que igual puedo ver al ojo cómo está el disco (muchas FFFFFF y muchos 00000 en algún tramo).

Lo del `stderr` es un tema aparte... el profesor dio una respuesta súper completa el semestre pasado, así que haré copy-paste de ella en una respuesta separada.

**Comment by Geeermy** [comment]
@cruz :
En Linux cada vez que se escribe algo, esto se debe hacer en un destino (un archivo, una posición de memoria, un dispositivo de I/O). Por defecto hay un destino estándar que se conoce como stdout (salida estándar) y es la manera de referirse a "la pantalla". Cada vez que haces printf("...") es equivalente a ejecutar fprintf(stdout, "..."). Así mismo existe un dispositivo de entrada por defecto que es stdin (entrada estándar) y es la manera de referirse a "el teclado".

Sin embargo, una cosa son los mensajes que el programa imprime debido a su ejecución normal, y otra son los mensajes que ocurren debido a un error, excepción, warning, segmentation fault, o información que genera el programa, pero que no está relacionada con su flujo normal de ejecución. Este destino se conoce como stderr (standard error) y se refiere al recipiente de los mensajes de error. Ahora bien, este destino por defecto es el mismo que stdout, o sea la pantalla. Por eso, al escribir mensajes en stdout o en stderr, saldrán todos en la pantalla. Pareciera entonces que son lo mismo y que el requisito del enunciado no tiene sentido (casi).

Sin embargo es posible redirigir cada uno de estas impresiones a destinos separados. Esta respuesta muestra varios ejemplos.

Por ejemplo, si tu programa crfs.c dice esto:

printf("Mensaje a stdout\n");
fprintf(stderr, "Mensaje a stderr\n");
Si ejecutas ./crfs simdisk.bin, la salida en pantalla será

Mensaje a stdout
Mensaje a stderr
que es lo esperado. Sin embargo si ejecutas ./crfs simdisk.bin 2> file-err.txt, entonces la salida en pantalla dirá

Mensaje a stdout
mientras que el archivo file-err.txt contendrá la línea

Mensaje a stderr
De la misma manera, si ejecutas: ./crfs simdisk.bin > file-out.txt, la salida en pantalla será

Mensaje a stderr
y el archivo file-out.txt contendrá

Mensaje a stdout
En ocasiones, cuando un programa imprime muchas líneas en pantalla, más de las que una terminal normal alcanza a mostrar (o implica hacer mucho scroll para revisarlo) puede ser más conveniente redirigir las líneas de stdout a un archivo. De esta manera, después de la ejecución (el programa debe terminar porque solamente entonces se cierra el archivo) puedes abrir el archivo en un editor y analizarlo completamente. Al momento de hacer esta redirección, no se mostrará nada en la pantalla, salvo los mensajes que vayan a stderr.

Separar los mensajes que son "de error" y los mensajes "normales" en destinos distintos, aunque por defecto ambos sean a la pantalla, permite posteriormente separarlos y poder aislar únicamente los mensajes que advierten anormalidades de aquellos que representan una ejecución normal.

Espero que esto te ayude.

**Comment by DanielCarrascoFalcon** [comment]
Te pasaste!! Muchas gracias!!
