### ISSUE TITLE
[Proyecto SSOO] Lista de contenidos de "simdiskfilled.bin"

### ISSUE THREAD

**Issue by sfga** [IIC2333/foro-2019-2#45]
Hola,

   ¿donde está la lista de contenidos del disco `simdiskfilled.bin`?. No he logrado encontrarla luego de buscar en el servidor.

Gracias por la atención,

Saludos.

**Comment by IchottMano** [comment]
Hola! 
Disculpa la demora 😅 
Estos son los directorios:
 - El directorio raíz
![raiz](https://user-images.githubusercontent.com/26393051/65825827-06282280-e252-11e9-8444-2bb1d1f2d339.png)
Donde dir1 y dir2 son los directorios
- dir1
![dir1](https://user-images.githubusercontent.com/26393051/65825839-2526b480-e252-11e9-9e71-b287a33fcfde.png)
 - dir2
![dir3](https://user-images.githubusercontent.com/26393051/65825845-3ff92900-e252-11e9-8ca2-02585883a1ea.png)
Y finalmente dir3
- dir3
![dir3](https://user-images.githubusercontent.com/26393051/65825856-54d5bc80-e252-11e9-8ecf-696d7f96bef3.png)

Saludos!

**Comment by sfga** [comment]
Gracias por la pronta respuesta
