### ISSUE TITLE
[Proyecto SSOO] Bonus Errores de Input

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2333/foro-2019-2#46]
Hola!

Para el bonus, en cuanto a la estandarización y manejo de errores, hay que considerar errores de _input_?, Por ejemplo, que nos pasen un _path_ no absoluto, un disco que no exista, una dirección negativa o mayor a la máxima, etc.

Saludos!

**Comment by Geeermy** [comment]
¡Hola!

Ustedes pueden decidir hasta qué punto se lleva a cabo el manejo. Más que otorgarles más puntos por tener manejos infinitos de casos de uso, se otorgará el bonus completo si **todas** las funciones de la API tienen documentación y un manejo adecuado de posibles excepciones. El mal uso de las funciones no me parece tan relevante, por ejemplo, en comparación con excepciones más críticas, como que una carpeta ya no tenga más entradas de directorio disponibles al momento intentar crear un nuevo archivo dentro de ella.

Espero que esto sirva para priorizar cómo quieren llevar a cabo el manejo de errores. No está mal querer manejar los casos que planteas, pero hay excepciones más críticas que deberían considerar antes de pensar en errores de usuario. 😁

**Comment by KnowYourselves** [comment]
Muchas gracias! Me queda claro.
