### ISSUE TITLE
[Proyecto SSOO] Unidad de tamaño de archivo en bloque índice + Consulta de tamaño de un archivo del disco 'simdiskfilled.bin'

### ISSUE THREAD

**Issue by sfga** [IIC2333/foro-2019-2#47]
Hola,

   ¿en qué unidades se escribe el tamaño de archivo (primeros 4 bytes) en un bloque índice?

   Por último, ¿me podrían decir el tamaño del archivo /`dir/subdir/altera.mp4` del disco `simdiskfilled.bin`?

Gracias por la atención.

**Comment by IchottMano** [comment]
Hola!

El tamaño de los archivos está en bytes.

El tamaño de altera.mp4 es de 52169460 bytes.

Saludos!
