### ISSUE TITLE
[Proyecto SSOO] Consulta estructura de sistemas de archivos

### ISSUE THREAD

**Issue by seba608** [IIC2333/foro-2019-2#48]
Hola,

Podrían explicar con un poco más de detalle qué esperan de esto:

![s1](https://user-images.githubusercontent.com/26118304/65843139-62e51500-e306-11e9-9d86-a32482ae2cfe.png)

Hay que crear un struct por cada uno de esos ítems? Para implementar la API tenemos que hacer uso de estas structs y no recorrer el archivo binario directamente?

Saludos!

**Comment by Geeermy** [comment]
¡Hola!

Basta con que implementen el `struct crFILE` que les pedimos. Con "representación" básicamente nos referimos a que las funciones de su API manejen bien esos tipos de bloque. Por ejemplo, si implementan bien las funciones relacionadas a los bloque directorio (`cr_ls`, `cr_mkdir`, etc.), se considera que esa representación la tienen correcta.

Espero que quede claro. :-)

**Comment by seba608** [comment]
Gracias!
