### ISSUE TITLE
Dudas mk_dir

### ISSUE THREAD

**Issue by gnacrur** [IIC2333/foro-2019-2#49]
Hola, tenía dos dudas sobre esta función. Primero, en otra issue hablaban de crear directorios dentro de otros directorios. No obstante en el enunciado solo dice que creemos una carpeta con nombre foldername y yo había asumido que estaba bien simplemente crearlos bajo el directorio padre. Se que nos dicen que hagamos supuestos pero en la otra issue se hablaba de poder crear directorios dentro de otros entonces no se si es básico incluirlo o no.
Por otra parte, al crear un directorio, debo escribir una entrada en el bloque  del directorio donde lo estoy creando. Mi duda es que si sabiendo que esta vacío, deben o no apuntar a un nuevo bloque directorio los últimos 4 bytes de la entrada? Gracias!

**Comment by Geeermy** [comment]
¡Hola!

1) En concreto, `foldername` es una ruta, por lo que es perfectamente válido tener una llamada, por ejemplo: `cr_mkdir("./foo/bar")` para crear la carpeta `bar` dentro de la carpeta `foo`, ubicándose esta dentro de `root`. El supuesto que ustedes pueden hacer, en realidad, es cómo hacer el manejo si, por ejemplo, la carpeta `foo` no existiera en `root` (¿Creamos la carpeta? ¿Tiramos un mensaje de error? Eso es decisión de ustedes).

2) Si no está especificado en el enunciado (me parece que no), entonces puedes hacer el supuesto. Lo más sencillo sería asumir siempre que sí, dado que en otro caso la función de crear archivos (`cr_open`) tendría que hacerse cargo de verificar si está el puntero o no (y de no estarlo, asignar uno). Quizás sería mejor que se hiciera de esa forma para no perder bloques, pero eso ya viene a ser decisión de ustedes.

¡Espero haber sido claro! :)
