### ISSUE TITLE
Funcionamiento de fork()

### ISSUE THREAD

**Issue by fguinez** [IIC2333/foro-2019-2#5]
Hola!

No me quedó totalmente claro de la clase cómo funciona la ejecución de `PATENT` y `CHILD` luego de hacer `fork`. ¿Una es primero? ¿Son en 'paralelo'? ¿Cómo funciona exactamente este paralelo?

Repasando las diapositivas corrí [este](http://iic2333.ing.puc.cl/slides/1-proc.html#/creation-fork-l-result) código, sin embargo el output es diferente, siempre muestra `PARENT` primero:

```
Antes de fork()
PARENT: child_pid is 15653
PARENT: a is 42
CHILD: a is 43
```

Por lo tanto, probé 2 modificaciones:

**1. Un `sleep` antes de los `printf` de `PARENT`**, dando como resultado:
```
Antes de fork()
CHILD: a is 43
PARENT: child_pid is 15436
PARENT: a is 42
```
**2. Muchos `printf` de relleno antes de imprimir `PARENT`**, dando como resultado:
```
1: Antes de fork()
2: printf de relleno
     ...
15: printf de relleno
16: CHILD: a is 43
17: printf de relleno
     ...
81: printf de relleno
83: PARENT: child_pid is 15537
84: PARENT: a is 42
```

Con esto me queda bastante claro que se ejecutan en paralelo, pero no entiendo bien cómo. ¿Por qué `CHILD` aparece luego de 14 acciones de relleno en `PARENT`?¿No sería más lógico que aparezca junto con la primera o segunda acción?

Lo mismo con el código original, me parecen lógicas las salidas `CHILD`, `PARENT`, `PARENT` y `PARENT`, `CHILD`, `PARENT`. Pero `PARENT`, `PARENT`, `CHILD` no me calza con una ejecución en 'paralelo', es como si `CHILD` partiera después de un tiempo y `PARENT` se continua ejecutando inmediatamente después de hacer `fork`.

Un saludo✌️

**Comment by cruz** [comment]
Hola Francisco,
Muy buen análisis el que hiciste. La respuesta corta es: no está mal; depende del sistema operativo.

La respuesta larga.

Más que decir "en paralelo", después de hacer `fork()` decimos que ejecutan de manera **concurrente**. Que sean concurrentes significa que ambos son "elegibles para ejecutar", o que ambos están en estado _ready_ ó _running_. Como verás, esa definición aplica tanto en el caso que haya una sola CPU (solo puede haber uno proceso en estado _running_), o si hay más de una.

El concepto de correr "en paralelo" se aplica cuando hay más de una CPU involucrada (en el mismo o en más computadores), y en ese caso pueden haber dos o más procesos ejecutando (_running_) **realmente** al mismo tiempo. 

Una vez que están los dos procesos en memoria, el `PARENT` y el `CHILD`, es decisión del sistema operativo (a través del _scheduler_) el decidir quién ejecuta primero. En los sistemas modernos el _scheduler_ es el de tipo interactivo, el cual asigna un tiempo _q_ a cada proceso, luego lo interrumpe, hace un cambio de contexto, y pone a otro a ejecutar. Lo más probable es que después de hacer `fork()`, se creó el `CHILD` (con su PCB y se puso en la cola _ready_), pero el `PARENT` todavía no había gastado todo su tiempo _q_, y siguió ejecutando inmediatamente. Lo que hiciste en tus dos experimentos está muy bien porque ahí forzaste a que el `PARENT` pasara a estado _waiting_ (caso 1), o que gastara el tiempo _q_ que le quedaba (caso 2). 

Una ejecución que sea vea como en la slide que indicaste, es poco probable, ya que el `fork()` tendría que terminar justo antes del cambio de contexto), pero no imposible. Por lo tanto, no puedes confiar en que siempre va a seguir ejecutando el `PARENT` inmediatamente, a menos que lo fuerces con una instrucción de sincronización, o una de bloqueo, como `sleep`.

Espero que esto ayude.

Saludos,
Cristian

**Comment by fguinez** [comment]
Gracias! Me queda mucho más claro.

**Comment by Geeermy** [comment]
¡No cierren las _issues_! Sirven de referencia para todos/as. :smile:
