### ISSUE TITLE
bits para Bitmap no son suficientes

### ISSUE THREAD

**Issue by Dyoma3** [IIC2333/foro-2019-2#50]
No se si estoy cachando huevo, pero segun mis calculos hay 128 * 32 = 4096 bits para bitmap, pero hay 2^20 bloques. En este caso no hay suficientes bit para saber que bloques estan libres o no.

**Comment by Geeermy** [comment]
¡Hola!

El cálculo es incorrecto. Primero, al ser el disco de 1 GB y los bloques de 1 KB, tenemos 2^30 B / 2^10 B = 2^20 bloques en el disco.

Ahora, el bitmap representa un bloque por BIT. Tenemos 128 bloques de bitmap y, al ser estos de 1 KB, estos son de 2^10 Byte, lo que sería igual a 2^13 BIT. Por lo tanto:

Bits bitmap = 128 * 2^13 = 2^7 * 2^13 = 2^20.

La cantidad de bits que tenemos repartida en todos los bloques de bitmap es, entonces, igual a la cantidad de bloques existentes en el disco. No hay inconsistencias ni excepciones que deban manejar con eso.

¡Espero que quede claro!

**Comment by Dyoma3** [comment]
gracias! habia anotado mal un dato
