### ISSUE TITLE
[Proyecto SSOO] Escribir en disco 

### ISSUE THREAD

**Issue by josefinabengoa** [IIC2333/foro-2019-2#51]
Hola!

¿Qué recomiendan hacer en el cr_write? Escribir directamente en el disco o escribir primero en un buffer y luego que la función cr_close tome este buffer y lo escriba en el disco (y actualice el bitmap). En el primer caso entonces ¿qué haría cr_close (ademas de liberar memoria)?
Pregunto porque me confunden dos frases del enunciado:

- Al final de cr_write sale: "Si se produjo un error porque no pudo seguir escribiendo, ya sea porque el DISCO se llenó" ¿entonces se debe escribir en disco en el cr_write?

- En cr_close sale: "Debe garantizar que cuando esta función retorna,  elarchivo se encuentra actualizado en DISCO" ¿entonces cr_close escribe en el disco?

Gracias!

**Comment by Geeermy** [comment]
¡Hola!

**TL;DR solo usa `cr_write` para escribir y `cr_close` para liberar memoria.**

1) Al final va a depender de lo que prefieran ustedes y de cómo modelen el problema en general. Lo típico (y recomendado) es que usen `cr_write` para escribir directamente y `cr_close` solo para liberar la memoria de las estructuras.

2) No es necesario que `cr_write` escriba directamente en el disco si no lo programan de esa forma, pero sí debe suceder que `cr_write` sea capaz de indicarle al usuario que YA NO SE PUEDE seguir escribiendo si: (i) no quedan bloques disponibles; o (2) se supera el tamaño máximo de archivo (eso NO pasará en este caso, dado que el tamaño máximo de archivo es mayor al del disco). Entonces, si lo modelan de forma que `cr_close` actualice el contenido en disco y no `cr_write`, tendrían que implementarlo de forma que `cr_write` pueda ser capaz de detectar si se puede o no escribir... podrán notar que esto puede complicar de forma innecesaria el problema, por lo que yo al menos no lo recomendaría.

3) En `cr_close` se indica eso, más que todo, porque en el pasado han existido grupos que solo actualizan los bloques en la ejecución del programa y, al abrir el disco de nuevo, este **no está actualizado** (es decir, no sobreescriben el disco binario). Entonces, esa descripción se indica solo para explicitar que al final del uso de la API su contenido DEBE haber sido modificado (si es que fue en modo escritura).

Espero que con eso quede más claro el panorama. :-)
