### ISSUE TITLE
[Proyecto SSOO] cr_write append o overwrite

### ISSUE THREAD

**Issue by josefinabengoa** [IIC2333/foro-2019-2#52]
Hola!

¿La función cr_write implica sobreescribir el archivo en caso de que ya exista o hacer un append del nuevo contenido en caso de que ya exista? 

Gracias!

**Comment by Geeermy** [comment]
¡Hola! (de nuevo)

La idea es aplicar `cr_write` sobre archivos abiertos en modo `w`, y esto se **debería hacer** solo en archivos que no han sido creados previamente. Es decir, no se pueden sobreescribir archivos. Una vez que hacen `cr_close`, el archivo no debería poder volver a tocarse (salvo que lo eliminen).

Ahora... ustedes pueden asumir que sí se puede y hacer un manejo al respecto, pero esto ya sería decisión propia y parte de sus supuestos.

Espero haber aclarado la duda. :)
