### ISSUE TITLE
[Proyecto SSOO] Metadata "tamaño archivo"

### ISSUE THREAD

**Issue by josefinabengoa** [IIC2333/foro-2019-2#53]
Hola!

Me pregunto que información debemos guardar en los primeros cuatro bytes de un bloque indice? Es el tamaño del archivo "completo" (i.e. considerando también todos los bloques de direccionamiento e índice), o solo los bloques de datos?

Otra opción sería que solo fuese el tamaño del contenido real (distinto de los bloques de datos que se reservan, puesto que estos pueden no estar llenos).

Gracias!

**Comment by Geeermy** [comment]
¡Hola! (de nuevo x 2)

El tamaño es en bytes y **solo del contenido real**. La idea es que esto sea así porque así, al hacer `cr_read`, puedes deducir la cantidad de punteros a bloques que debe existir y, además, hasta qué punto leer dentro de un bloque (para no incluir ruido en el archivo).

Espero que esta y todas tus dudas hayan quedado claras jaja. :grin:
