### ISSUE TITLE
Pregunta cr_open()

### ISSUE THREAD

**Issue by pfarellano** [IIC2333/foro-2019-2#54]
Hola !! tengo una duda porque estoy un poco confundida con los argumentos que recibe cr_open. En el enunciado, en la parte de ejecución hay un ejemplo que dice cr_open("test.txt", "w"), donde el primer argumento sería el nombre de un archivo que está en el disco, pero en la parte donde se definen las funciones dice que cr_open recibe como primer argumento el path del archivo que se busca abrir, entonces no estoy segura de cómo implementarlo. ¿o al final "test.txt" es además de ser el nombre del archivo su path y está en root?

**Comment by Geeermy** [comment]
¡Hola!

`"test.txt"` no solo es el nombre del archivo, sino que **también** su ruta. Así que sí, es la ruta de un archivo que se encuentra en `root`. Mucho ojo con eso en general, en la función `cr_mkdir` se recibe el argumento `foldername`, pero este **también** es una ruta. En general vamos a trabajar con rutas (que incluyen el nombre del archivo/carpeta) y no directamente con su nombre.

Espero que quede claro. :)

**Comment by pfarellano** [comment]
siii !! me quedo clarísimo !! te pasaste, muchas gracias :)
