### ISSUE TITLE
[Proyecto] cr_close

### ISSUE THREAD

**Issue by nmaturana97** [IIC2333/foro-2019-2#55]
Hola, no me queda muy claro lo que se debe hacer en cr_close(archivo). Desde mi punto de vista esto solo lo que hace es liberar memoria, pero no estoy seguro de esto.

**Comment by Geeermy** [comment]
¡Hola!

Depende de la modelación, pero sí, lo más típico es que libere la memoria de la estructura del archivo. Está bien si es solo eso. :)

¡Mucho éxito!
