### ISSUE TITLE
Edición disco

### ISSUE THREAD

**Issue by gnacrur** [IIC2333/foro-2019-2#56]
Hola, estaba haciendo la función cr_mkdir y quiero escribir una entrada en un bloque directorio. Mi idea era escribir el disco para que así los cambios queden guardados en el instante. El problema es que fopen en modo "w" me borra completamente el disco y no puedo sobre-escribir solo algunos bytes de este. Quería saber si hay alguna forma de editar el disco y así no tener que sobreescribirlo entero solo para cambiar una entrada de 32 bytes. Se que se puede usar el modo "a" pero esto empieza a escribir al final por lo que no me imagino que me pueda servir. Si es que no se puede hacer de esta forma o hay algo que no estoy viendo apreciaría mucho cualquier sugerencia, gracias!

**Comment by IchottMano** [comment]
Hola!

Puedes usar el modo "r+" para tanto leer como escribir en el disco, sin borrarlo. También existe el modo "w+", pero este si borra los contenidos.

Saludos!
