### ISSUE TITLE
[Proyecto] cr_unload y destino

### ISSUE THREAD

**Issue by ouhenio** [IIC2333/foro-2019-2#57]
Hola! 

No me queda claro si para `cr_unload` se deben copiar los elementos en la ruta de `dest`, o bien tienen que copiarse renombrándolos para que coincida su nuevo path con `dest`. 

Por ejemplo, ¿la idea es que funcione de esta forma?

 ```
// se copia main.c a file.c en /mi_pc/folder/
cr_unload('/home/folder/main.c', '/mi_pc/folder/file.c')
```

¿O bien se espera que su funcionamiento sea?
```
// se copia main.c en /mi_pc/folder/
cr_unload('/home/folder/main.c', '/mi_pc/folder')
```

**Comment by Geeermy** [comment]
¡Hola!

Si bien lo pensamos para el segundo caso (que mantengan su nombre original en el disco), al no estar explicitado en el enunciado ustedes pueden hacer el supuesto que quieran. No obstante, me parece que el segundo ejemplo es el más sencillo y directo.

¡Éxito! :-)
