### ISSUE TITLE
[Proyecto SSOO] Buffer cr_write

### ISSUE THREAD

**Issue by josefinabengoa** [IIC2333/foro-2019-2#58]
Hola! 

- ¿El buffer que recibe cr_write es de bytes? o puede tener un tipo variable el arreglo?

- ¿Nosotros nos tenemos que encargar de leer el archivo y pasarlo al buffer que va a recibir  cr_write? En este caso, ¿debería quedar a criterio nuestro el cómo manejar el buffer (si es de bytes o variable) o en el momento de la evaluación ustedes van a llamar a cr_write con buffers de distinto tipo? ¿o el buffer es un puntero tipo FILE (puntero directo al archivo)?

Gracias!

**Comment by Geeermy** [comment]
¡Hola!

- Al ser `void *` el _buffer_, le puedes pasar del tipo que te acomode al usar la función en `main.c` o en otras funciones, por ejemplo, `unsigned char *` (que me parece el más cómodo para trabajar con bytes).

- La función solo tiene que estar hecha de forma que yo, para probar sus funciones, pueda hacer uso de un _buffer_ de bytes cualquiera para escribir sobre un archivo (que debería haber sido abierto antes con `cr_open`). Donde va a quedar a criterio suyo cómo manejar el _buffer_ va a ser en la función `cr_load`, dado que en esta van a tener que hacer uso de `cr_write` para ir cargando los archivos desde su computador al disco binario, lo que implicará que tendrán que definir un _buffer_ con el contenido de cada archivo a escribir (y bueno... espero que no lo hayan pensado como algo independiente de `cr_write`, dado que la idea es que saquen provecho de esa función si es que está bien definida).

Si te quedan dudas, consulta no más. :-)
