### ISSUE TITLE
[proyecto ssoo] cr_read, Contenido txt

### ISSUE THREAD

**Issue by mramirez7** [IIC2333/foro-2019-2#59]
Hola! estoy tratando de leer el archivo /dir/texto.txt, quería saber si su contenido tiene o no sentido para testear la función y si es así, podrían escribir el contenido del archivo? para ver si se está leyendo completo.

**Comment by mplazadelosreyes** [comment]
tengo la misma duda!

**Comment by Geeermy** [comment]
¡Hola!

Este es el archivo original escrito en el disco.

[texto.txt](https://github.com/IIC2333/foro-2019-2/files/3695048/texto.txt)

¡Mucho éxito! :-)
