### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by benjamimo1** [IIC2333/foro-2019-2#6]
Hola! Tengo una duda con el csv:

·"nombre ejecutable es el nombre del programa externo ejecutado."

Si ejecuto:
 `python3 test.py`
quien es el programa externo? Python3 o test.py. Pregunto por que de ser test.py y no la primera palabra en cada string, habria que diferenciar el caso en el que se ejecutan programas compilados ./test de aquellos en que se ejecutan por parte de un software externo, como el caso de Python.

**Comment by Geeermy** [comment]
¡Hola!

Sería `python3`, ya que este es el que recibe como argumento el _script_ `test.py` a ejecutar. Lo definimos así porque, como bien dices, en otro caso tendrían que diferenciar ambos casos (distando del objetivo de la tarea).

¡Mucho éxito! :)

**Comment by benjamimo1** [comment]
Genial! Gracias

**Comment by seba608** [comment]
Hola @Geeermy,

Me queda una duda con respecto a lo anterior. Si es que ejecuto dos programas con python3, ¿cómo podría diferenciar que línea del output corresponde a cada programa? O no va a pasar eso con los test que utilizarán?

**Comment by Geeermy** [comment]
¡Hola!

Lamentablemente, sí podría pasar. :-(

Lo que deberían hacer es imprimir el _output_ **en el orden de aparición en el archivo de entrada**. No está explícito en el enunciado, pero es la única forma directa en la que se pueden diferenciar programas externos del mismo nombre. Si guardas los nombres de los ejecutables en un arreglo de _strings_ al momento de llevar a cabo la lectura, no debería haber problema con respetar ese orden.

¡Mucho éxito!

**Comment by Geeermy** [comment]
**Nota importante:** Para los que ya hayan terminado la tarea y hayan escrito el archivo de salida según el término de cada proceso (por ejemplo), no se preocupen. Nos enfocaremos en que los programas de mismo nombre (ej. `python3`) puedan ser diferenciados según el tiempo de término, así que no es necesario que modifiquen sus tareas. :nerd_face:

Aviso ahora antes de que me lleguen maldiciones al correo. :sweat_smile:

**Comment by haarenas** [comment]
Aprovecho esta issue para hacer un par de preguntas:

- Tomando como ejemplo el nombre de un ejecutable en el enunciado, al momento de escribir el csv, es valido dejar el nombre del ejecutable como ```./hola``` o tiene que ir como ```hola```

- El tiempo tiene que ir en un formato especifico? (milisegundos, segundos, etc)

**Comment by Geeermy** [comment]
¡Hola

- Puedes dejarlo como viene en el archivo de entrada: `./hola`

- Segundos. :-)

**Comment by seba608** [comment]
@Geeermy Muchas gracias por las respuestas!
