### ISSUE TITLE
[Proyecto] Archivo con todos sus bloques indirectos

### ISSUE THREAD

**Issue by gbordoni** [IIC2333/foro-2019-2#60]
Queria saber si en el disco que nos entregan hay algun archivo que utilize todos los tipos de bloques de direccionamiento indirecto para guardar sus datos y poder proba cr_rm

saludos

**Comment by Geeermy** [comment]
¡Hola!

Lamentablemente, ninguno en `simdiskfilled.bin` los usa todos. El archivo más grande, `altera.mp3`, hace uso de los punteros de direccionamiento indirecto doble, que sería lo más cercano. No obstante, de funcionar bien para ese caso veo difícil que no funcione para el caso triple. Lo bueno es que sirve de motivación para que prueben haciendo uso de `cr_load` con un archivo que pese más de (252 + 256 + 256*256)KB. 😁 (Y es algo que deben tener en cuenta el día de la corrección, de todas maneras).

¡Mucho éxito! :)
