### ISSUE TITLE
[Proyecto SSOO] Discos utilizados para la corrección

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2333/foro-2019-2#61]
Hola!

Para el momento de la corrección podremos utilizar diskfilled.bin? O solo diskformat.bin?

Gracias!

**Comment by Geeermy** [comment]
¡Hola!

Pueden utilizar ambos. La idea es que a partir de ellos ustedes elaboren la demo (`main.c`) de forma que podamos ver todas las funcionalidades que hayan implementado.

¡Que estés bien! (:

**Comment by mplazadelosreyes** [comment]
La corrección será este viernes?

**Comment by Geeermy** [comment]
¡Lo informaremos en un rato!
