### ISSUE TITLE
AC06 Pregunta sobre NTFS

### ISSUE THREAD

**Issue by benjamimo1** [IIC2333/foro-2019-2#62]
Segun me han comentado, la alternativa correcta incluye la alternativa "Una ventaja de NTFS sobre FAT es que remueve los limitantes sobre tamaño máximo de archivo y de partición, que afectaban a los sistemas FAT." aun cuando esto no es asi.
Pues el tamaño maximo es: 16 ExaBytes , no infinito.
Que se puede hacer al respecto?
http://www.ntfs.com/ntfs_vs_fat.htm

**Comment by Geeermy** [comment]
¡Hola!

A lo que apunta esa alternativa es que NTFS elimina esa restricción que limita a FAT, no que el tamaño máximo es infinito (ningún sistema de archivos con estructura definida lo permite). De esa expresión no se deduce que el tamaño máximo de archivo sea infinito, si se hubiera querido transmitir eso se habría explicitado.

Espero que se entienda.

¡Que estés bien! :grin:
