### ISSUE TITLE
Cantidad de clientes y partidas

### ISSUE THREAD

**Issue by dedarritchon** [IIC2333/foro-2019-2#66]
Si ya hay 2 clientes jugando una partida, es posible que un 3er y 4to cliente quieran jugar otra partida al mismo tiempo? o cuando hayan 2 clientes se rechazan otras conexiones?

**Comment by nivek0o0** [comment]
El enunciado original solo menciona 2 clientes por servidor. Esto significa que el servidor debe rechazar (_ignorar_) otras conexiones luego de aceptar los primeros 2 clientes.

Pero añadimos un **bonus** si deseas implementar más de 2 clientes en un mismo juego/servidor.
