### ISSUE TITLE
desconexión del cliente

### ISSUE THREAD

**Issue by dedarritchon** [IIC2333/foro-2019-2#67]
El cliente debe tener la opción de desconectarse en cualquier momento? por ejemplo mientras está estableciendo la conexión? (luego de recibir el paquete "Connection Established" y "Ask Nickname", y el servidor está esperando un "Return Nickname".)

**Comment by dedarritchon** [comment]
O por ejemplo cuando el servidor manda un "Connection Established", luego solo puede mandar un "Ask Nickname", o tambien podría mandar un "Disconnect"?

**Comment by nivek0o0** [comment]
Pueden asumir que no habrán paquetes `Disconnect` durante la fase de **conexión**. Esta fase será limpia y secuencial.
Por lo tanto, durante la conexión el cliente no tiene la opción de abandonar. Esa opción aparece cuando comienza el juego y le llegan sus cartas.
