### ISSUE TITLE
Opciones del cliente/servidor y "Error Bad Package"

### ISSUE THREAD

**Issue by dedarritchon** [IIC2333/foro-2019-2#68]
No me queda claro cuando tendríamos que ocupar el "Error Bad Package", si en teoría el cliente solo puede hacer lo que le permitamos en las opciones. (El servidor sabe en todo momento lo que el cliente le puede a mandar y el cliente solo puede mandarle esos paquetes).

**Comment by nivek0o0** [comment]
Ese paquete está pensado como una respuesta cuando al cliente o al servidor le llega un ID desconocido, osea, que no está definido en la lista del enunciado.

Su utilidad es principalmente el debuggeo cuando se conectan clientes y servidores de distintos grupos, para que quede registro en el **log** de que uno de los dos se equivocó en enviar un paquete.

Si tu comunicación entre cliente y servidor es perfecta, no deberías utilizar nunca ese paquete.
