### ISSUE TITLE
Error compilar Server en macOS

### ISSUE THREAD

**Issue by ignacioaraya1995** [IIC2333/foro-2019-2#69]
Hola,

Estoy teniendo problemas al intentar compilar el main.c del cliente y del server. Me aparece el siguiente mensaje:

<img width="572" alt="Screen Shot 2019-10-24 at 23 13 45" src="https://user-images.githubusercontent.com/21697653/67538178-b6a00f80-f6b4-11e9-890b-214c8e665762.png">

Acabo de actualizar mi SO a macOS Catalina.

Agradecería si alguien me puediese ayudar a buscar una forma que me corra.

Gracias!

**Comment by nivek0o0** [comment]
Pudiste solucionarlo ya? De ser así podrías escribir cómo lo hiciste por si otros tienen el mismo problema
