### ISSUE TITLE
Multiprogramación vs Multitasking

### ISSUE THREAD

**Issue by Kitaps** [IIC2333/foro-2019-2#7]
Hola, 

tenía una duda de contenido respecto a estas dos definiciones. 
Según tengo entendido multiprogramación es tener a varios procesos en memoria, y multitasking es hacer que pasen procesos en parallelo. 

Si cuando un programa no está usanco la CPU pero aun no termina, entonces el cambiar a otro proceso, eso es multiprogramación o multitasking?

Gracias

**Comment by cruz** [comment]
Hola @Kitaps ,

TL;DR Tal como lo describes es **multiprogramación**

Creo que en la primera palabra querías decir **multiprogramación**. En ese caso sí, es lo que dices. Es la capacidad de tener a varios procesos en memoria simultáneamente (no dice nada sobre en qué orden se ejecutan). **Multitasking** como también dices es que puedan correr "en paralelo", aunque el término más preciso es que corran de manera "concurrente".

Paréntesis: Que sean **concurrentes** significa que ambos son "elegibles para ejecutar", o que ambos están en estado _ready_ ó _running_. Como verás, esa definición aplica tanto en el caso que haya una sola CPU (en la cual sólo puede haber un proceso en estado _running_ a la vez), o si hay más de una. El concepto de correr "en paralelo" se aplica más bien cuando hay más de una CPU involucrada (en el mismo o en más computadores), y en ese caso pueden haber dos o más procesos ejecutando (_running_) **realmente** al mismo tiempo.

> Si cuando un programa no está usanco la CPU pero aun no termina, entonces el cambiar a otro proceso, eso es multiprogramación o multitasking?

Aquí yo te contra-preguntaría: ¿por qué no está usando la CPU?.

Lo que describes es posible gracias a la multiprogramación. Se trata de un proceso que no ha terminado, pero que tampoco está usando la CPU. Posiblemente está en estado _sleeping_ ó _blocked_ hasta que algo ocurra que lo haga salir de ahí (_input_ del usuario, lectura de disco, mensaje de red, etc). En ese caso, el sistema operativo saca de ejecución al que está esperando (para que no espere en la CPU), y pone a otro de los que tiene en memoria.

¿Cuándo sería _multitasking_? Cuando tienes la capacidad de interrumpir al que está corriendo, para que entre otro. En ese caso, el proceso que no está usando la CPU no es porque no quiera usarla o porque esté esperando que pase algo, sino que el _scheduler_ del sistema operativo decidió que ahora le tocaba el turno a otro proceso, interrumpió al que estaba en la CPU, lo puso en la cola _ready_, e hizo un cambio de contexto a un nuevo proceso.

Resumiendo, el solo hecho de tener procesos en memoria y ser capaz de hacer un cambio de contexto a otro proceso _cuando el que está en la CPU deja de avanzar_ es **multiprogramación**. Cuando además tienes una política de turnos e interrupciones (una política de _scheduling_), para que todos los procesos que quieren usar la CPU (estado _ready_) puedan avanzar en un cierto periodo de tiempo, entonces tienes **multitasking** y se dice que esos procesos son _concurrentes_.

En tu pregunta técnicamente es multiprogramación, pero si el que deja de ocupar la CPU sale porque lo interrumpieron para que avance otro, sería multitasking.

**Comment by Kitaps** [comment]
Muchas gracias, ahora me queda perfectamente claro. 

> Creo que en la primera palabra querías decir multiprogramación. 

Verdad, se me pasó.
