### ISSUE TITLE
Redundancia con Start Conection

### ISSUE THREAD

**Issue by CmPoblete** [IIC2333/foro-2019-2#70]
Hola, el paquete start conection no es un poco redundante? Para enviar este paquete el usuario ya debe estar conectado al socket del servidor, entonces deberiamos hacer que el cliente pueda solicitar conectarse (aunque ya este conectado) y recibir una respuesta del servidor?

**Comment by nivek0o0** [comment]
@CmPoblete no, no es reduntante. Piensa en el paquete **StartConnection** como una forma de solicitar unirse a una partida por parte de un cliente que desea jugar. 

Imagina que pueden haber otros clientes conectados mediante sockets al servidor que no juegan, sino que tienen otras funciones y por lo tanto no mandan el paquete en cuestión.

**Comment by sfga** [comment]
Hola @nivek0o0 , te quería plantear la siguiente situación:

En base a esto
> Imagina que pueden haber otros clientes conectados mediante sockets al servidor que no juegan, sino que tienen otras funciones y por lo tanto no mandan el paquete en cuestión.

y lo que mencionaste en #64 

>Solo la parte del recibir las cartas y enviar la palabra debe ser interactiva y simultánea entre los jugadores (el servidor no puede quedarse esperando la respuesta de un solo jugador, debe alternar entre ambos y recibir la respuesta que llegue primero). La parte inicial de la conexión y la parte final donde se pregunta por un nuevo juego pueden ser secuenciales.

¿Cuál sería el flujo de acción para la parte inicial de la conexión si consideramos esos clientes que se conectan al socket y no manifiestan intención de jugar?

A mi parecer, no podría ser secuencial, por lo siguiente: si el primer cliente que se conecta al socket del servidor no envía respuesta sobre si quiere jugar o no, va a implicar que el servidor se va a quedar esperando "infinitamente" por la respuesta de este cliente.

Además, tendría que considerar "slots" adicionales para potenciales clientes (sea que quieran jugar o no) para los cuales el servidor tendría que estar atento "simultaneamente" (y no secuencialmente) para ver si manifiestan su intención de jugar.

La verdad no sé me ocurre como tratar este caso, quizás utilizar alguna especie de timeout para una conexion entrante que la elimine si no manifiesta opción de jugar, pero esto chocaría con el "derecho" de los clientes a conectarse al servidor y no jugar. Sobre la alternativa de tener slots adicionales desconozco un número razonable, si es que se permite la conexion de clientes que no quieren jugar. Por ejemplo, la cantidad de conexiones de clientes que no quieren jugar podría ser tan grande que no habrían slots disponibles para la cantidad mínima de clientes que si quieren jugar.

Gracias por la atención.

**Comment by nivek0o0** [comment]
Hola @sfga, lo de los clientes que se conectan y no juegan era una situación hipotética para demostrar que el paquete no es redundante. 

En el proyecto solo deben manejar **2** clientes que van a jugar (o **N** si hacen el bonus).
