### ISSUE TITLE
Payload de la accion 'Send Cards"

### ISSUE THREAD

**Issue by sfga** [IIC2333/foro-2019-2#72]
Hola,

   ¿hay alguna razón para enviar los dos conjuntos de palabras a cada cliente?. Antes de leer en detalle el enunciado, me parecía razonable enviar solo el conjunto de palabras que le corresponde a cada cliente, pero al revisar el documento me dí cuenta de esto y quise preguntar.

Gracias por la atención.

**Comment by felipecr00** [comment]
Hola :)
Si entiendo bien tu pregunta, a ambos clientes les debe llegar el mismo par de cartas. La razón es porque se debe desplegar el mismo contenido para ambos clientes, no hay un conjunto de palabras que le pertenezca sólo a un cliente.

**Comment by sfga** [comment]
Entiendo. Entonces ambos clientes al recibir el par de cartas ven esto:

![image](https://user-images.githubusercontent.com/20782942/67720306-56f67c80-f9b2-11e9-8e6d-c6b9bf60409c.png)

Como el usuario tenía que adivinar, pensé que solo debía recibir una sola carta de palabras exclusiva para él (i.e si tiene las dos cartas, no tiene que adivinar la palabra repetida, basta con que revise que palabra se repite en ambas cartas).

Gracias por contestar.

**Comment by felipecr00** [comment]
Exactamente 👍, el usuario chequeará cuál es la palabra en común en ambas cartas y luego la envía.

**Comment by ghost** [comment]
El payload puede ser un string de este formato? 

4TENO145PIANO07COELEMU710PICHIDEGUA79NOVIEMBRE87CARRERA87CONSEJO38HOSPITAL39EMPEDRADO05PINTO27CABALLO39RESULTADO17BAHAMAS1210ESCARABAJO09WATERPOLO16TEORIA126SEMANA37BALLENA110PORTEZUELO1

De no poder ser así, en el array podríamos mandar todo en ints?

**Comment by nivek0o0** [comment]
@Jj1martinez Como se menciona en la issue #73, se pueden mezclar **ints** y **chars** en el mismo arreglo, todo depende de la forma en que los escribes. Lo importante es que debes mandar un cuatro como un 4 y no un '4'.
Te sugiero practicar con el servidor y el cliente que les entregamos.
