### ISSUE TITLE
Duda protocolo estándar: tipo de dato

### ISSUE THREAD

**Issue by mafillol** [IIC2333/foro-2019-2#73]
Hola!

Para 'Send Cards' fueron muy específicos con la forma de enviar y leer cada dato del Payload, pero para las demás no me queda muy claro.
Para 'Send IDs', 'Start Game', 'Scores', 'Response Word', 'Round Winner/Loser', 'End Game', 'Game Winner/Loser' y  'Answer New Game' , ¿debemos interpretar los datos como enteros?

Gracias de antemano.

**Comment by felipecr00** [comment]
Hola :)

Así es, deben enviarlos como int.
'Send IDs'
'Start Game', 
'Scores'
'Response Word', 
'Round Winner/Loser', 
'End Game', 
'Game Winner/Loser' 
'Answer New Game'

Saludos!!

**Comment by mafillol** [comment]
Ok. Muchas gracias :)

**Comment by mplazadelosreyes** [comment]
Hola!
Estamos usando  la función server_send_message que ustedes subieron y que recibe los argumentos (int client_socket, int pkg_id, char * message), queríamos saber si importa que por ejemplo si tengo el id = 1 para Send IDs si lo envío como '1' en formato char ya que así lo recibe la función, en vez de como tipo int en el parámetro de message

**Comment by mplazadelosreyes** [comment]
Otra duda que tengo es que en send cards el enunciado dice que mandemos el paquete así:
![Captura de pantalla 2019-10-30 a la(s) 19 35 40](https://user-images.githubusercontent.com/37154771/67904226-80e3a680-fb4c-11e9-8d50-00ff2f3f975d.png)

Lo que nos complica es que no sabemos como podemos crear un array que mezcle chars y ints para construirlo antes de mandarlo

**Comment by nivek0o0** [comment]
Hola
**Respecto a la primera pregunta:**
Sí, importa muchísimo si envías un 1 o un '1', porque estos dos tipos de dato se almacenan de manera distinta en tu computador. El primero se almacena simplemente como el n° **1**, mientras que el caracter '1' se almacena, según la tabla de conversión ASCII como el n° **49**. Por lo tanto, tu receptor vería un 49 como _package_id_ que no corresponde a nada. Según recuerdo la función que mencionas del ejemplo lo recibe como parámetro **int** y lo manda como **int**. 

**Respecto a la segunda pregunta:**
En la práctica, cualquier dato lo puedes escribir o leer como **int** o como **char** sin ningún problema, ya que el compilador se encarga de la traducción ASCII. Esto implica que al momento de asignar el valor de una variable **char** o en una posición de un arreglo de **chars** tienes las siguientes formas equivalentes:
char myVar = 65;
char myVar = 'A';
myCharArray[0] = 65;
myCharArray[0] = 'A';

Esto significa que asignar el caracter 'A' es lo mismo que asignar un 65. Ambos van a guardar un 65 (en binario obviamente) en la memoria.

La diferencia sucede cuando el receptor quiere leer ese valor. Si lo guarda en una variable de tipo **char**, al imprimirlo como %c verá una 'A' y al imprimirlo como %d verá 65. (Independiente de qué forma lo haya escrito el emisor)

Entonces en el paquete SendCards tu puedes tener tu arreglo de puros **chars** pero escribirlo así:
char myArray[<algo>];
myArray[0]=64;
myArray[1]='X';
myArray[2]=65;

Y para que el mensaje se _entienda_ el receptor debe leerlo como **int**, **char**, **int**. De lo contrario leerá cualquier cosa. Por ejemplo, si leyera puros **char** vería '@' 'X' 'A'.

También funcionaría tener un arreglo de puros **int** y escribir 64 88 65, o escribir 64 'X' 65. Da igual. Lo que importa es cómo lo lee y printea el receptor.

**En resumen**:
Los **chars** son un tipo de dato multiuso, porque permiten guardar letras (caracteres), numeros hexadecimal, numeros binarios, etc. Están un nivel por encima de los numeros enteros en términos de funcionalidad. Asignarle un numero entero a una variable de tipo char es básicamente saltarte este nivel. 

se entiende? :smile:

**Comment by KnowYourselves** [comment]
@nivek0o0 Hola!

Respecto a tu forma de manejar los `int`, lo estamos intentando hacer de exactamente la misma forma, pero cuando el int en cuestión es un 0 no funciona. Específicamente, cuando leemos el payload del cliente "omite" completamente su existencia.

Por ejemplo, si tenemos un payload de la forma `3CAT04PATO5` al momento de leer la primera palabra nos leería el tamaño (3) y la palabra (CAT) bien, pero al leer la columna omitiría el 0 y tomaría el siguiente valor, 4.

Hemos estado mucho rato intentando ver de donde podría salir este problema y todavía no tenemos ni la más mínima idea. Sabes a que se podría deber? Gracias!

**Comment by Dyoma3** [comment]
![image](https://user-images.githubusercontent.com/17127676/68398092-f48c4180-0152-11ea-905a-789382f50524.png)
Cuando los valores son mayores a 128 se envian con otro valor. Cual seria el protocolo en este caso? enviarlo como 170 y que el cliente sepa que -86 corresponda a ese valor?

**Comment by KnowYourselves** [comment]
@Dyoma3 si sabes que el mensaje en especifico puede ser muy grande le puedes poner unsigned char (char sin signo) y te lo va a hacer bien

**Comment by nivek0o0** [comment]
@KnowYourselves 

Hola, acabo de probar el envío del byte 0 entremedio de otras letras y funciona perfecto.

Te adjunto el ejemplo de la ayudantía con algunas modificaciones. Básicamente metí un 0 en la tercera posición del mensaje de bienvenida que el servidor le envía al primer cliente.

[ayudantia-ejemplo-byte0.zip](https://github.com/IIC2333/foro-2019-2/files/3822545/ayudantia-ejemplo-byte0.zip)

El error que tienen tal vez se deba a una forma incorrecta de leer del socket. 
¿Están leyendo de la forma:
`1 byte N bytes 1 bytes   ....  1 byte M bytes 1 byte `... así 19 veces?

**Comment by nivek0o0** [comment]
@Dyoma3 

Lo que sucede es que un byte común y corriente está implementado para almacenar enteros desde -128 hasta 127 (_convención_), ya que ocupa el primer bit como signo y quedan los otros 7 para la magnitud

Pero nosotros sabemos dos cosas: 
1. el payloadSize nunca será negativo
2. con 8 bits (1 byte) podría representar hasta el 256. 

Entonces la solución pasa por guardar **ese byte** en una variable de tipo `unsigned int`.

**Comment by gnacrur** [comment]
@nivek0o0 Entonces, deberíamos interpretar como int los chars que están en posición del array donde debería haber un int. Respecto a eso, no nos traerá problema el hecho que los primeros símbolos de ascii incluyen cosas como backspace, o termino de texto por ejemplo? Al menos al imprimirlo se que sale bastante mal pero no estoy seguro si eso no tendrá otras consecuencias. Lo que estábamos haciendo antes nosotros era sumarle un '0' pero el problema con eso es que no sería compatible con otras tareas supongo.

**Comment by Dyoma3** [comment]
@gnacrur yo porlomenos interpreto como int los char que se supone representan un numero. No tengo ningun problema para leerlo si interpreto bien los datos. Para el send cards uso unsigned char eso si.

**Comment by nivek0o0** [comment]
@gnacrur tu compañero @Dyoma3 tiene razón respecto a la interpetación.

Luego, para qué vás a imprimir como %c una posición donde sabes que va un int, mejor lo imprimes como %d y así sale el dígito y no el caracter raro.
