### ISSUE TITLE
Duda log.txt

### ISSUE THREAD

**Issue by josefinabengoa** [IIC2333/foro-2019-2#74]
Hola! 

No me queda claro dónde se debe ubicar el archivo log.txt, ¿está bien que lo tengamos en la carpeta del servidor y que el server vaya escribiendo en el archivo todos los movimientos de paquetes? O sea, ¿el cliente nunca escribe en el log.txt?

Gracias!

**Comment by felipecr00** [comment]
Hola :)
Ambos (Cliente y Servidor) escriben sus propios logs. Los guardan en las carpetas de cada uno y listo. Es decir, los paquetes de entrada y salida del cliente en un archivo, y lo mismo para el servidor en otro archivo 😄 

Saludos!!
