### ISSUE TITLE
Error Bad Package

### ISSUE THREAD

**Issue by mafillol** [IIC2333/foro-2019-2#75]
Hola!

Agradecería si me pudieran aclarar algunas dudas con este paquete y como usarlo.

- Me podrían decir algunos ejemplos específicos de un paquete mal construido.
- Si el payload de 'Start Connection' no es vacío, ¿se considera un paquete mal construido?
- Una vez enviado al usuario, ¿qué se espera del comportamiento del servidor y  de los clientes? ¿servidor envía luego el paquete de 'Disconnect' a los clientes y termina? ¿deben seguir corriendo servidor y cliente eternamente?¿servidor envía 'Disconnect' al usuario que no genera el error y termina, mientras que el usuario que genera el error termina por su cuenta luego de recibir el paquete 'Error Bad Package'?
- ¿Cómo interpreto el contenido del payload mal construido que ha llegado al servidor para log.txt?¿Puedo asumir que es un array de caracteres para poder escribirlo en el archivo?

Gracias de antemano.

**Comment by felipecr00** [comment]
Hola!

- Un ejemplo de uso de ese paquete es si envías un id que no corresponde.
- Un ejemplo para un paquete sería si el tamaño indicado para el payload de este no corresponde a lo que efectivamente recibes en el payload.
- La verdad es que como interpreten el paquete (en el cliente o servidor) es decisión de ustedes mientras nos expliquen en el readme que fue lo que hicieron.
- Es una buena idea escribirlo de esa forma en el archivo :)

Saludos!

**Comment by felipecr00** [comment]
Para el payload de 'Start Connection' , el mensaje del paquete que envías sería algo del estilo `char msg[1+1] = {1, 0}`, en ese caso estas indicando que el tamaño del payload es 0 y no estas enviando nada para el payload. Ahora tomando la pregunta, **"Si el payload de 'Start Connection' no es vacío, ¿se considera un paquete mal construido?"**, efectivamente estaría mal construido porque si el payload no es vacío entonces el servidor debería estar esperando un payload que no esta definido (ni sabe que hacer con eso), y además le estas entregando un tamaño al payload que tampoco hemos definido.

Saludos!

**Comment by seba608** [comment]
Hola @felipecr00,

Solo para estar seguro, podrías especificar cuales son los paquetes que tienen payloads vacíos?

Saludos!

**Comment by felipecr00** [comment]
Hola @seba608 :)
Por supuesto, por parte de los que envía el **cliente**:
`Start connection`
`Disconnect`

Por parte de los que envía el **server**:
`ConnectionEstablished`
`AskNickname`
`AskNewGame`
`Disconnect`
`Error Bad Package`

@mafillol Solo por simplicidad, prefiero que en `Error Bad Package` simplemente notifiquen que el paquete fue mal recibido, no agreguen ningún detalle del contenido. 

Saludos!!

**Comment by seba608** [comment]
@felipecr00 Muchas gracias!

**Comment by mafillol** [comment]
Si para los paquetes que tienen payload vacío, el servidor recibe un payload con size=1  pero con valor '\0' ¿también se considera mal construido? 
Porque en el fondo sigue siendo un mensaje vacío.

**Comment by felipecr00** [comment]
Si el cliente envía un payload con algún tamaño (size = 1 por ejemplo), el servidor a priori debe ser capaz de leer la información contenida en ese payload. Pero luego que es lo que haría con esa información?. Ahora imagina una implementación de otro server que no maneja recibir algún payload para aquellos id que tienen un payloadSize = 0, no les servirá tener la información de un 
size = 1, porque tampoco estarían gestionando leer ese payload a través de un receive. 

En resumen, por convención, es mejor  implementar algo de este estilo `msg[1+1] = {1, 0}`, indicando que no hay un payload por enviar al ser de size=0 y pensar en esos paquetes como "Paquetes de transición", porque en teoría no existe información alguna en esos paquetes más que enviar/recibir el id para gatillar una nueva acción. Respondiendo a tu duda, bajo lo anterior, si estaría mal construido.

Espero haber respondido tu pregunta 😄 
Saludos!

**Comment by mafillol** [comment]
Es que en las funciones client_send_message y server_send_message del ejemplo de la ayudantía consideran payloadSize = strlen(message) + 1, contando así el caracter nulo. ¿Esto estaría incorrecto? ¿No debemos considerar nunca el caracter nulo?  o ¿Podemos asumir que siempre va a estar?

**Comment by felipecr00** [comment]
En la implementación que tienen disponible (tanto server y cliente) para que puedan testear no se considera el caracter `\0` en los envíos, así que estas en lo correcto, no lo consideren. Así es más fácil comparar palabras y el largo es igual a la cantidad de letras de cada palabra.

Más que incorrecto, lo de la ayudantía es sólo un ejemplo. En este caso, si desean printear las palabras, tendrán que agregar ese caracter, pero eso lo gestionan una vez recibido 😄 

Saludos!

**Comment by mafillol** [comment]
Ahora si me quedó claro. Muchas gracias.
