### ISSUE TITLE
[Proyecto Redes] Duda bonus imágenes

### ISSUE THREAD

**Issue by elramirezv** [IIC2333/foro-2019-2#76]
Hola!

Tengo una duda con respecto al comportamiento que debería tener el programa al enviar las fotos cuando hay un ganador/perdedor.

Cuando le envío el paquete de ID: 64 al cliente, el servidor debería esperar una respuesta antes de enviarlas?? o solo hacerlo de inmediato??

Pregunto porque si el cliente no tiene implementada la funcionalidad de recibir imágenes, entonces no podría manejarlo y podría caerse(?) mientras el servidor sigue enviando paquetes. En cambio, si se le envía una respuesta (Por ejemplo: "OK" o "Bad package"), ahí el servidor podría saber si enviarlas o no.

El problema es que no hay ningún mensaje tipo "OK" en la tabla que me sirva para eso :(

**Comment by nivek0o0** [comment]
Hola @elramirezv123 
El protocolo está pensado como que el servidor envía todos los segmentos de la imagen de forma consecutiva, sin necesitar una confirmación. 

Por lo tanto, si el cliente no tiene implementado una forma de recibirlas, **no se debe caer**, tendrán que implementar al menos una forma de librar el buffer donde quedaron encolados todos esos bytes. 

Lo bueno es que ya saben exactamente cuándo el servidor envía las imágenes: justo después de la respuesta de los jugadores al AskNewGame.

**Comment by sfga** [comment]
Hola @nivek0o0, te quería preguntar sobre esto: 

> Lo bueno es que ya saben exactamente cuándo el servidor envía las imágenes: justo después de la respuesta de los jugadores al AskNewGame.

¿Los paquetes de imágenes solo se mandan cuando los clientes no quieren seguir jugando (al parece en el server de ejemplo se hace de esta manera) o se mandan sin importar las respuestas de los clientes?

Gracias por la atención.

**Comment by nivek0o0** [comment]
La verdad es que en el enunciado no sale especificado cuándo deben ser enviados, así que queda a tu criterio.

Por ejenplo, nuestra implementación de servidor envía las imágenes cuando los clientes no quieren seguir jugando.

Recuerda especificarlo en el Readme para poder corregirlo.
