### ISSUE TITLE
Falta paquete Send IDs en el diagrama

### ISSUE THREAD

**Issue by dedarritchon** [IIC2333/foro-2019-2#77]
Hola, en el diagrama del enunciado falta el paquete Send IDs.
Este debería ir despues de Opponent Found y enviarlo a ambos clientes al mismo tiempo?

Saludos

**Comment by felipecr00** [comment]
Ups 😅 efectivamente se paso ese paquete en el diagrama. Estás en lo correcto, va después de `Opponent Found` y el server se lo envía a cada cliente al mismo tiempo.

Saludos!
