### ISSUE TITLE
Incompatibilidad Multiples clientes con Mensajes 

### ISSUE THREAD

**Issue by CmPoblete** [IIC2333/foro-2019-2#78]
Hola, leyendo ciertos mensajes del protocolo de comunicacion, siento que el protocolo no es compatible con multiples clientes, especificamente en los mensajes de scores (que hay que enviar un byte por cada score, pero el cliente no sabe contra cuantos otros clientes esta jugando y por lo tanto no podria saber cuanto leer) y de round winner/losser (en caso en que dos clientes empaten y se este jugando con mas de dos personas, no se podria enviar quien gano, ya que habria un empate).

**Comment by nivek0o0** [comment]
Hola, es muy probable que deban hacer ligeras modificaciones a los mensajes del protocolo si deciden hacer el Bonus de múltiples clientes. Estas modificaciones quedan a su criterio y el bonus se corregirá dentro del mismo grupo, no jugando contra otros grupos. 

Para que esas modificaciones no afecten el normal funcionamiento entre 2 clientes, podrían activar el Bonus mediante algún _flag_ por consola al momento de la ejecución.
