### ISSUE TITLE
Desconexión repentina del servidor

### ISSUE THREAD

**Issue by sfga** [IIC2333/foro-2019-2#79]
Al final de la página 2 e inicio de la página 3 del enunciado del proyecto se dice lo siguiente:

> Importante: Se debe implementar el protocolo estándar de esta tarea de tal modo que su cliente pueda comunicarse con el servidor elaborado por usted, el de sus compañeros o de los ayudantes. Esto es importante porque la corrección incluye el poder conectarse con otras tareas. Si el servidor se desconecta repentinamente, el cliente debe ser capaz de controlar dicho evento e informar al jugador sobre la desconexión.

¿En que parte del flujo el servidor puede desconectarse repentinamente? Hasta el momento, tengo entendido que los clientes pueden desconectarse "repentinamente" (entiendo lo siguiente: desconexión = solicitar una desconexión mediante un mensaje) en cualquier momento, no así el servidor, el cual sólo solicita una desconexión después del rechazo de los jugadores para iniciar un juego nuevo (diagrama de la página 10 del enunciado).

Gracias por la atención.

**Comment by felipecr00** [comment]
Hola :)

Tienes razón, el diagrama contempla  la desconexión en el flujo ideal del juego. Sin embargo, si la implementación del server de sus compañeros se cae, o el servidor de ustedes se cae al momento de ejecutar el flujo del juego, deben ser capaces de notificar la desconexión correspondiente al cliente. De alguna forma están gestionando los errores por parte del servidor de cara al cliente a través de esta desconexión.

Saludos!

**Comment by sfga** [comment]
Gracias por contestar.

Primera duda: ¿A que nivel se deben manejar estas "caídas" del server"? De momento se me ocurren dos opciones:

1. A nivel de interrupciones (según #65, esto no aplicaría)
2. Cancelar la operación del server (y enviar la notificacion de desconexion) si se detectan condiciones que van a generar un error futuro. Por ejemplo, si al abrir el archivo .csv de palabras, este resulta ser nulo, entonces cancelar la operación general del server y envíar la notificación de desconexión a los clientes.

Segunda duda: ¿El manejo de caídas sería solo en el flujo de juego (flujo de juego = diagrama de linea punteada azul en la página 10 del enunciado)?
![image](https://user-images.githubusercontent.com/20782942/68093609-3f1d6d80-fe76-11e9-8a6e-f24f209b653b.png)

**Comment by felipecr00** [comment]
Claro, la diferencia con esas interrupciones es que son generadas al presionar las teclas mencionadas en #65, las cuáles efectivamente no les pedimos que gestionen. Sin embargo, el cliente debe ser capaz de abstraerse de los errores que se puedan producir en el servidor (ya que sin un servidor activo no tiene sentido la conexión del cliente). 

Un servidor podría presentar un error (un segfault por ejemplo), y no podemos dejar "colgado" al cliente. Es sobre este tipo de casos que deben preparar a sus clientes. Un **hint** para manejar esto es revisar que el socket siga vigente.

Respondiendo a la segunda pregunta, **¿El manejo de caídas sería solo en el flujo de juego (flujo de juego = diagrama de linea punteada azul en la página 10 del enunciado)?**, efectivamente será así. Evaluaremos el flujo que respete el diagrama que les hemos propuesto.

En resumen, el servidor debe ser capaz de manejar la desconexión voluntaria de los clientes, mientras que el cliente debe manejar la desconexión accidental del servidor.

Saludos!
