### ISSUE TITLE
[Tarea1] Memory Leaks

### ISSUE THREAD

**Issue by MrEarle** [IIC2333/foro-2019-2#8]
Hola,

Cuando corro mi código con _valgrind_, cada vez que termina un hijo de mi programa principal, me reporta sus _memory leaks_. Al ver donde se producen (con `--leak-check=full --show-leak-kinds=all`), me muestra que los leaks de los hijos provienen de cosas hechas en el programa principal antes de crear los hijos.
Además _valgrind_ reporta que el programa principal no tiene _memory leaks_.

Acaso _valgrind_ reporta los _memory leaks_ de los hijos porque aun no libero la memoria de lo  usado en el programa principal? De ser así el caso (incluyendo que no hayan _memory leaks_ en el programa principal), cuenta para el puntaje de "manejo de memora"?

**Comment by Pudindin** [comment]
Hola!
A mí al principio no me pasaba que valgrind reportara memory leaks de los hijos, valgrind ni siquiera los mencionaba. Sin embargo, de pronto sí lo hizo, pero con sólo 1 de varios. 
Me di cuenta de que lo que estaba pasando es que, después de hacer fork(), la syscall excec() fallaba. Por eso, en vez de convertirse en otro proceso, el hijo seguía siendo idéntico al padre. Como consecuencia, tenía 2 procesos iguales corriendo. Y al ser el mismo, valgrind me reportaba en ambos. En cuanto arreglé el fallo de exec() (llamaba a un programa que no existía), ya no me reportó doble.
Quizás lo que te ocurre sea lo mismo; que el excec falla al convertir el hijo en otro proceso. Espero que te sirva!

**Comment by MrEarle** [comment]
Efectivamente es eso lo que me esta pasando, pero no porque un exec no este funcionando, si no que creo un hijo que no hace un exec. Por eso pregunto si igual cuenta para el puntaje de manejo de memoria, ya que eventualmente si se libera esa memoria que reporta como _leaked_ antes de terminar el programa.

**Comment by IchottMano** [comment]
Hola!

El problema radica en que, cuando tu ejecutas fork(), estas clonando al proceso padre, creando un hijo casi exactamente igual al padre.
Al hacer esto, efectivamente estas copiando la memoria del proceso original, por lo que el hijo tiene pedidos segmentos de memoria iguales a los del padre (los punteros son los mismos y la memoria pedida tiene el mismo tamaño).

Es por esto, que si el hijo no termina por medio de un exec, es necesario que liberes la memoria pedida en ámbos procesos, tanto el padre como el hijo, como no lo haces, se reporta que hay memoria en el hijo que no está siendo liberada.

Saludos!

**Comment by MrEarle** [comment]
Ahi me quedo muy claro. Gracias!
