### ISSUE TITLE
Funcionamiento juego

### ISSUE THREAD

**Issue by Dyoma3** [IIC2333/foro-2019-2#84]
En el enunciado se relaciona el puntaje con el numero de intentos solamente, pero no con haber contestado antes o despues que el oponente. No me hace sentido el juego si no es asi, ya que simplemente podria tomarme todo el tiempo que quiera para encontrar las palabras repetidas.

**Comment by felipecr00** [comment]
Hola :),
Efectivamente la dinámica del juego es asociar el puntaje al número de intentos en la respuesta. Y claro, puedes tomarte todo el tiempo del mundo si quisieras. Pero recuerden que la idea del juego es hacer algo que permita comprender el uso de los protocolos y sockets; la implementación del juego es un detalle, y esa opción se veía rápida de implementar sin tener que considerar el uso de tiempo de respuesta del jugador.

**Comment by nivek0o0** [comment]
Fue una simplificación de la tarea. Si quieres tomarlo como desafío puedes implementarlo y que se active a través de un flag que le pasas a tu servidor, pero no tendrá puntaje.
