### ISSUE TITLE
Reglas del Juego

### ISSUE THREAD

**Issue by camichavez** [IIC2333/foro-2019-2#85]
Hola! con mi grupo tenemos una duda de como funciona el juego que quisiéramos resolver por favor.

Lo que entendimos del juego es:
1. En una ronda los jugadores (X e Y) parten con el mismo par de tarjetas.
2. Por cada vez que traten de responder, para el segundo intento y tercer intento ambos reciben necesariamente el mismo par de cartas. (3 intentos por cada ronda)
3. **Cuando un jugador responde correctamente ambos pasan a la siguiente ronda. O puede pasar que uno responde correctamente pasando a la siguiente ronda y el otro se quede respondiendo en los intentos que le queden en su ronda actual?**

Estamos medios confundidos con el punto 3, muchas gracias!

**Comment by nivek0o0** [comment]
Hola @Cschavez 
La ronda termina cuando ambos jugadores responden correctamente o se quedan sin intentos. 

En otras palabras, en todo instante de tiempo la ronda es la misma para ambos jugadores.

**Comment by Cschavez** [comment]
Y para cada intento la carta mostrada es distinta a la del intento anterior pero igual entre los jugadores, es correcto eso?

**Comment by Cschavez** [comment]
Y para cada intento la carta mostrada es distinta a la del intento anterior pero igual entre los jugadores, es correcto eso?

**Comment by camichavez** [comment]
Y para cada intento la carta mostrada es distinta a la del intento anterior pero igual entre los jugadores, es correcto eso? O las cartas solo cambian para cada ronda?

**Comment by felipecr00** [comment]
Hola @Cschavez  :),
Para cada **intento** del jugador el par de cartas sigue siendo es el mismo 😄 
La ronda se da por terminada una vez ambos jugadores responden la palabra correcta del par de cartas o si se quedan sin intentos. Luego, viene el siguiente par de cartas y así sucesivamente.
 
Saludines

**Comment by nivek0o0** [comment]
Es decir, cada ronda tiene un único par de cartas.

**Comment by ghost** [comment]
Pero como hay que enviar el paquete SendWords nuevamente, la palabra repetida podría estar en distinta posición?
Estarían siendo las mismas 19 palabras solo que varía la línea en donde esta la repetida.

**Comment by nivek0o0** [comment]
No es necesario desordenar las tarjetas al reenviarlas durante la ronda
