### ISSUE TITLE
Error con Send Cards

### ISSUE THREAD

**Issue by camichavez** [IIC2333/foro-2019-2#86]
Hola! con mi grupo tenemos un error al enviar las cartas desde el servidor al cliente. En el servidor sabemos que estamos formando bien el mensaje, y que se está guardando correctamente en un buffer. Sin embargo, cuando llega al cliente este no llega con el mismo largo y pareciera llegar por partes, a lo que el cliente se vuelve "loco" y empieza a recibir parte del mensaje original dentro de otros if a los que se entraba cuando el servidor enviaba otro tipo de mensaje (vimos y el servidor no está enviando nada nuevo al cliente después de send cards).
Aquí un ejemplo:
![image](https://user-images.githubusercontent.com/37157327/68806742-3599bf80-0645-11ea-834c-e7e8831e4c0c.png)
Está medio engorroso pero por ejemplo dice
`Comienza la partida: palabras
Un contrincante se ha detectado: palabras
`
Y en verdad esos prints corresponden al inicio de la partida, que se ven así originalmente:
![image](https://user-images.githubusercontent.com/37157327/68807433-8a8a0580-0646-11ea-8520-a0982bdf4fc7.png)

Intentamos convertir el buffer en un unsigned char pero el problema sigue. Agradeceríamos infinitamente su ayuda, gracias!

**Comment by nivek0o0** [comment]
Hola, están trabajando en github o algo similar? Podrían darnos acceso para revisar la implementación, porque aquí es muy difícil saber qué esta pasando.

**Comment by frvalenzuela** [comment]
Hola @nivek0o0 ! 
Le dimos acceso a nuestro repositorio .

Saludos !

**Comment by nivek0o0** [comment]
Cómo están tan seguros de que el servidor está construyendo bien el paquete?
Tienen un printeo de las cartas (o el paquete) construidas por el servidor?

**Comment by camichavez** [comment]
Si tenemos! está en la branch send-card-aeroport-branch, en server/src/packages/packages.c en la línea 119 hasta 136, está descomentado ahora. Perdón por no mencionarlo antes.

**Comment by nivek0o0** [comment]
La raíz del problema es que están considerando 20 palabras por carta, cuando en realidad son solo 10. Esto genera que la magnitud del payloadSize sea del orden de los ~300, y eso no cabe en 1 byte. Entonces el PayloadSize que el server le manda al cliente está incorrecto y por eso lee a trozos.

Si te fijas, el payloadSize de server/src/packages/packages.c line 111 es distinto al que se envía finalmente. 
el largo del paquete: 346 -> 101011010
lo que recibe el cliente:  90  ->  1011010 (truncado)

Y *OJO* con la función `strlen()`, ya que ella cuenta hasta encontrar un byte 0, que es equivalente al caracter nulo terminador de los strings `\0`. Esto les generará problemas cuando una palabra vaya en la posición 0

Y no entendí qué cosa rara están haciendo con los Scores como strings, cuando deberían ser simplemente números enteros.

**Recuerden testear con los `server` y `client` compilados que les subimos!**
Ánimo! :muscle:

**Comment by shantifabri** [comment]
Hola @nivek0o0, respecto a lo que dices del \0, nos dimos cuenta que nos estaba dando el mismo problema. ¿Hay alguna forma de obtener el largo de un array que contenga el byte 0 y después otros caracteres?

**Comment by nivek0o0** [comment]
@shantifabri 

Que yo sepa, no hay forma de obtener el largo de un arreglo después de haberlo creado. Piensa que el arreglo es solo una dirección de memoria, y desde allí puedes leer infinito hacia adelante hasta caer en SegFault.

Por eso, lo que deberían hacer es calcular y retornar el PayloadSize en la función que lo va construyendo palabra x palabra.

**Comment by shantifabri** [comment]
Pero entonces ¿cómo se puede mandar un payload que contenga un 0 y que no corte ahí el "string"? Porque nos pasa por ejemplo con los scores que al mandarlos como char array [score1, score2], si el primero es 0, ignora al segundo y le asigna cero aunque el valor sea otro. Creemos que eso ocurre porque lo lee como \0 entonces deja de leer lo que va a continuación. Pero no sabemos como resoverlo. Tambien nos trae problema con o que dices de si la palabra está en la posición 0.

**Comment by aeperalta** [comment]
Hola @nivek0o0, hay alguna solución para que un int 0 no corte un array de chars? Es decir, que no lo tome como el final del array, sino como un 0... Nos está pasando esto cuando hay un 0 entre medio de las cartas, y la solución de sumarle uno y luego restarle uno a cada valor (para no tener ceros), no será compatible con otros servidores/clientes. Hemos buscado en internet, pero no encontramos la solución. 
Saludos!

**Comment by nivek0o0** [comment]
Estan confundiendo el concepto de **string** con el de **payload**.

Un **payload** es simplemente un conjunto de _bytes_ almacenados en un buffer, nada más. Esos bytes pueden tomar valores del 0 al 255 o del -128 al 127 dependiendo de si los guardas en una variable unsigned o signed. Lo importante es que no tienen un significado per se. El 0 es un valor totalmente válido y normal.

Un **string** también es un conjunto de bytes, pero con la diferencia de que cada uno representa un símbolo/letra. Y la **convención** que adoptaron los creadores de C es que los string se terminan con un byte de valor 0, que representa el caracter '\0'.

Entonces podríamos decir que los sockets mandan payloads. Ellos no miran el valor y "dejan de leer o enviar". Ellos se encargan de transmitir exactamente los N bytes que les pasaste y hasta luego. 

Si tu decides interpretar ese payload como un string, el lenguaje va a pensar que el string termina cuando haya un byte 0, y el resto es basura. Pero esta interpretación es tu decisión, tu tienes el control de si quieres interpretar todo como un string, o interpretar a trozos (como se debe hacer para nuestro caso: int string int, int string int...).

En resumen:
-El int 0 no corta el array. Solo corta la impresión cuando lo imprimes en el formato %s, lo que es normal.
-La función strlen() no sirve para determinar el largo del paquete SendCards, porque éste no es 100% un string.
-Los sockets no dejan de leer cuando ven un 0, para ellos no importan los valores
-Lo que tienen que hacer con este paquete es leerlo con un for loop: obtienen el largo N de la palabra (int), leen los siguientes N bytes para formar la palabra(str), obtienen la posición(int). Todo eso repetido 20 veces.
