### ISSUE TITLE
Consulta Round Winner/Loser

### ISSUE THREAD

**Issue by seba608** [IIC2333/foro-2019-2#87]
Hola!

Estaba jugando con el server que ustedes subieron y me surgió una duda con la siguiente situación:

Ronda 1:
Jugador 1 acierta y en el primer intento y gana 5 puntos
Jugador 2 acierta en el segundo intento y gana 3 puntos. 
El ganador de la ronda es el Jugador 1

Ronda 2:
Jugador 1 acierta y en el segundo intento y gana 3 puntos
Jugador 2 acierta en el primer intento y gana 5 puntos. 
Arroja ronda empatada.

Si bien en el total de puntos van iguales a 8, en mi opinión el jugador 2 es el ganador de esa ronda y por eso no me hace sentido que arroje ronda empatada. Estoy entendiendo algo mal?

Saludos!

**Comment by nivek0o0** [comment]
Hola, efectivamente nuestro servidor tenía un :bug:. Estaba determinando el ganador de la ronda mirando el puntaje acumulado del juego y no el puntaje propio de la ronda.

Ya lo subí corregido. ¿Podrías probarlo y contarme si se arregló?
Gracias

**Comment by seba608** [comment]
Hola @nivek0o0,

Hice una prueba y funcionó bien!

Muchas gracias
