### ISSUE TITLE
[Tarea1] Interrupcion Ctrl+C

### ISSUE THREAD

**Issue by MrEarle** [IIC2333/foro-2019-2#9]
Hola,
No me queda claro en el enunciado el procedimiento al detectar una señal SIGINT en el programa principal. Cual de las siguientes opciones es la correcta?

1. Terminar los procesos que están corriendo. Si quedan más procesos por ejecutar, comenzar su ejecución (de a cuerdo al máximo de procesos concurrentes y de tiempo). Si no quedan más procesos, escribir el output y terminar.

2. Terminar los procesos que estan corriendo. Aun cuando falten procesos por ejecutar, escribir el output y terminar. En este caso, a los procesos que no alcanzaron a comenzar su ejecución, su output tendría tiempo de ejecucion 0 y  resultado 0 (aun cuando ni siquera empezó) o no se escriben en el output?

3. Ninguna de las anteriores y no estoy cachando nada

**Comment by Geeermy** [comment]
¡Hola!

La opción sería la **número 2**. el resto de los programas no alcanza su ejecución, lo que efectivamente implica que su término será "anormal" (dado que fueron "interrumpidos", aunque nunca ejecutaron realmente). La idea es que **SÍ** los escriban en el _output_, para que quede claro que no alcanzaron a ejecutar.

Estás cachando todo, no te preocupes. :grin: 

¡Mucho éxito!

**Comment by MrEarle** [comment]
Ok, muchas gracias!
